// Code generated by pigeon; DO NOT EDIT.

package parser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"

	"github.com/arizonahanson/oryx/pkg/ast"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "AST",
			pos:  position{line: 7, col: 1, offset: 68},
			expr: &actionExpr{
				pos: position{line: 7, col: 8, offset: 77},
				run: (*parser).callonAST1,
				expr: &seqExpr{
					pos: position{line: 7, col: 8, offset: 77},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 7, col: 8, offset: 77},
							label: "seq",
							expr: &ruleRefExpr{
								pos:  position{line: 7, col: 12, offset: 81},
								name: "Seq",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 7, col: 16, offset: 85},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Any",
			pos:  position{line: 12, col: 1, offset: 147},
			expr: &choiceExpr{
				pos: position{line: 12, col: 8, offset: 156},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 12, col: 8, offset: 156},
						name: "Null",
					},
					&ruleRefExpr{
						pos:  position{line: 12, col: 15, offset: 163},
						name: "Boolean",
					},
					&ruleRefExpr{
						pos:  position{line: 12, col: 25, offset: 173},
						name: "Number",
					},
					&ruleRefExpr{
						pos:  position{line: 12, col: 34, offset: 182},
						name: "String",
					},
					&ruleRefExpr{
						pos:  position{line: 12, col: 43, offset: 191},
						name: "Array",
					},
					&ruleRefExpr{
						pos:  position{line: 12, col: 51, offset: 199},
						name: "Map",
					},
					&ruleRefExpr{
						pos:  position{line: 12, col: 57, offset: 205},
						name: "Symbol",
					},
					&ruleRefExpr{
						pos:  position{line: 12, col: 66, offset: 214},
						name: "Expr",
					},
				},
			},
		},
		{
			name: "Seq",
			pos:  position{line: 15, col: 1, offset: 251},
			expr: &choiceExpr{
				pos: position{line: 15, col: 8, offset: 260},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 15, col: 8, offset: 260},
						run: (*parser).callonSeq2,
						expr: &seqExpr{
							pos: position{line: 15, col: 8, offset: 260},
							exprs: []interface{}{
								&zeroOrMoreExpr{
									pos: position{line: 15, col: 8, offset: 260},
									expr: &ruleRefExpr{
										pos:  position{line: 15, col: 8, offset: 260},
										name: "_",
									},
								},
								&labeledExpr{
									pos:   position{line: 15, col: 11, offset: 263},
									label: "first",
									expr: &ruleRefExpr{
										pos:  position{line: 15, col: 17, offset: 269},
										name: "Any",
									},
								},
								&labeledExpr{
									pos:   position{line: 15, col: 21, offset: 273},
									label: "rest",
									expr: &oneOrMoreExpr{
										pos: position{line: 15, col: 26, offset: 278},
										expr: &seqExpr{
											pos: position{line: 15, col: 27, offset: 279},
											exprs: []interface{}{
												&oneOrMoreExpr{
													pos: position{line: 15, col: 27, offset: 279},
													expr: &ruleRefExpr{
														pos:  position{line: 15, col: 27, offset: 279},
														name: "_",
													},
												},
												&ruleRefExpr{
													pos:  position{line: 15, col: 30, offset: 282},
													name: "Any",
												},
											},
										},
									},
								},
								&zeroOrMoreExpr{
									pos: position{line: 15, col: 36, offset: 288},
									expr: &ruleRefExpr{
										pos:  position{line: 15, col: 36, offset: 288},
										name: "_",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 17, col: 5, offset: 332},
						run: (*parser).callonSeq16,
						expr: &seqExpr{
							pos: position{line: 17, col: 5, offset: 332},
							exprs: []interface{}{
								&zeroOrMoreExpr{
									pos: position{line: 17, col: 5, offset: 332},
									expr: &ruleRefExpr{
										pos:  position{line: 17, col: 5, offset: 332},
										name: "_",
									},
								},
								&labeledExpr{
									pos:   position{line: 17, col: 8, offset: 335},
									label: "infix",
									expr: &ruleRefExpr{
										pos:  position{line: 17, col: 14, offset: 341},
										name: "Infix",
									},
								},
								&zeroOrMoreExpr{
									pos: position{line: 17, col: 20, offset: 347},
									expr: &ruleRefExpr{
										pos:  position{line: 17, col: 20, offset: 347},
										name: "_",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Expr",
			pos:  position{line: 22, col: 1, offset: 391},
			expr: &choiceExpr{
				pos: position{line: 22, col: 9, offset: 401},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 22, col: 9, offset: 401},
						run: (*parser).callonExpr2,
						expr: &seqExpr{
							pos: position{line: 22, col: 9, offset: 401},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 22, col: 9, offset: 401},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&labeledExpr{
									pos:   position{line: 22, col: 13, offset: 405},
									label: "seq",
									expr: &ruleRefExpr{
										pos:  position{line: 22, col: 17, offset: 409},
										name: "Seq",
									},
								},
								&litMatcher{
									pos:        position{line: 22, col: 21, offset: 413},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 24, col: 5, offset: 463},
						run: (*parser).callonExpr8,
						expr: &seqExpr{
							pos: position{line: 24, col: 5, offset: 463},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 24, col: 5, offset: 463},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&ruleRefExpr{
									pos:  position{line: 24, col: 9, offset: 467},
									name: "Seq",
								},
								&notExpr{
									pos: position{line: 24, col: 13, offset: 471},
									expr: &litMatcher{
										pos:        position{line: 24, col: 14, offset: 472},
										val:        ")",
										ignoreCase: false,
										want:       "\")\"",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Infix",
			pos:  position{line: 28, col: 1, offset: 559},
			expr: &ruleRefExpr{
				pos:  position{line: 28, col: 10, offset: 570},
				name: "OrExpr",
			},
		},
		{
			name: "OrOp",
			pos:  position{line: 30, col: 1, offset: 583},
			expr: &actionExpr{
				pos: position{line: 30, col: 9, offset: 593},
				run: (*parser).callonOrOp1,
				expr: &litMatcher{
					pos:        position{line: 30, col: 9, offset: 593},
					val:        "||",
					ignoreCase: false,
					want:       "\"||\"",
				},
			},
		},
		{
			name: "OrExpr",
			pos:  position{line: 33, col: 1, offset: 621},
			expr: &actionExpr{
				pos: position{line: 33, col: 11, offset: 633},
				run: (*parser).callonOrExpr1,
				expr: &seqExpr{
					pos: position{line: 33, col: 11, offset: 633},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 33, col: 11, offset: 633},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 33, col: 17, offset: 639},
								name: "AndExpr",
							},
						},
						&labeledExpr{
							pos:   position{line: 33, col: 25, offset: 647},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 33, col: 30, offset: 652},
								expr: &seqExpr{
									pos: position{line: 33, col: 31, offset: 653},
									exprs: []interface{}{
										&oneOrMoreExpr{
											pos: position{line: 33, col: 31, offset: 653},
											expr: &ruleRefExpr{
												pos:  position{line: 33, col: 31, offset: 653},
												name: "_",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 33, col: 34, offset: 656},
											name: "OrOp",
										},
										&oneOrMoreExpr{
											pos: position{line: 33, col: 39, offset: 661},
											expr: &ruleRefExpr{
												pos:  position{line: 33, col: 39, offset: 661},
												name: "_",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 33, col: 42, offset: 664},
											name: "AndExpr",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "AndOp",
			pos:  position{line: 37, col: 1, offset: 723},
			expr: &actionExpr{
				pos: position{line: 37, col: 10, offset: 734},
				run: (*parser).callonAndOp1,
				expr: &litMatcher{
					pos:        position{line: 37, col: 10, offset: 734},
					val:        "&&",
					ignoreCase: false,
					want:       "\"&&\"",
				},
			},
		},
		{
			name: "AndExpr",
			pos:  position{line: 40, col: 1, offset: 762},
			expr: &actionExpr{
				pos: position{line: 40, col: 12, offset: 775},
				run: (*parser).callonAndExpr1,
				expr: &seqExpr{
					pos: position{line: 40, col: 12, offset: 775},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 40, col: 12, offset: 775},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 40, col: 18, offset: 781},
								name: "EqlExpr",
							},
						},
						&labeledExpr{
							pos:   position{line: 40, col: 26, offset: 789},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 40, col: 31, offset: 794},
								expr: &seqExpr{
									pos: position{line: 40, col: 32, offset: 795},
									exprs: []interface{}{
										&oneOrMoreExpr{
											pos: position{line: 40, col: 32, offset: 795},
											expr: &ruleRefExpr{
												pos:  position{line: 40, col: 32, offset: 795},
												name: "_",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 40, col: 35, offset: 798},
											name: "AndOp",
										},
										&oneOrMoreExpr{
											pos: position{line: 40, col: 41, offset: 804},
											expr: &ruleRefExpr{
												pos:  position{line: 40, col: 41, offset: 804},
												name: "_",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 40, col: 44, offset: 807},
											name: "EqlExpr",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "EqlOp",
			pos:  position{line: 44, col: 1, offset: 880},
			expr: &actionExpr{
				pos: position{line: 44, col: 10, offset: 891},
				run: (*parser).callonEqlOp1,
				expr: &choiceExpr{
					pos: position{line: 44, col: 11, offset: 892},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 44, col: 11, offset: 892},
							val:        "==",
							ignoreCase: false,
							want:       "\"==\"",
						},
						&litMatcher{
							pos:        position{line: 44, col: 18, offset: 899},
							val:        "!=",
							ignoreCase: false,
							want:       "\"!=\"",
						},
					},
				},
			},
		},
		{
			name: "EqlExpr",
			pos:  position{line: 47, col: 1, offset: 928},
			expr: &actionExpr{
				pos: position{line: 47, col: 12, offset: 941},
				run: (*parser).callonEqlExpr1,
				expr: &seqExpr{
					pos: position{line: 47, col: 12, offset: 941},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 47, col: 12, offset: 941},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 47, col: 18, offset: 947},
								name: "CmpExpr",
							},
						},
						&labeledExpr{
							pos:   position{line: 47, col: 26, offset: 955},
							label: "rest",
							expr: &zeroOrOneExpr{
								pos: position{line: 47, col: 31, offset: 960},
								expr: &seqExpr{
									pos: position{line: 47, col: 32, offset: 961},
									exprs: []interface{}{
										&oneOrMoreExpr{
											pos: position{line: 47, col: 32, offset: 961},
											expr: &ruleRefExpr{
												pos:  position{line: 47, col: 32, offset: 961},
												name: "_",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 47, col: 35, offset: 964},
											name: "EqlOp",
										},
										&oneOrMoreExpr{
											pos: position{line: 47, col: 41, offset: 970},
											expr: &ruleRefExpr{
												pos:  position{line: 47, col: 41, offset: 970},
												name: "_",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 47, col: 44, offset: 973},
											name: "CmpExpr",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "CmpOp",
			pos:  position{line: 51, col: 1, offset: 1055},
			expr: &actionExpr{
				pos: position{line: 51, col: 10, offset: 1066},
				run: (*parser).callonCmpOp1,
				expr: &choiceExpr{
					pos: position{line: 51, col: 11, offset: 1067},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 51, col: 11, offset: 1067},
							val:        "<=",
							ignoreCase: false,
							want:       "\"<=\"",
						},
						&litMatcher{
							pos:        position{line: 51, col: 18, offset: 1074},
							val:        "<",
							ignoreCase: false,
							want:       "\"<\"",
						},
						&litMatcher{
							pos:        position{line: 51, col: 24, offset: 1080},
							val:        ">=",
							ignoreCase: false,
							want:       "\">=\"",
						},
						&litMatcher{
							pos:        position{line: 51, col: 31, offset: 1087},
							val:        ">",
							ignoreCase: false,
							want:       "\">\"",
						},
					},
				},
			},
		},
		{
			name: "CmpExpr",
			pos:  position{line: 54, col: 1, offset: 1115},
			expr: &actionExpr{
				pos: position{line: 54, col: 12, offset: 1128},
				run: (*parser).callonCmpExpr1,
				expr: &seqExpr{
					pos: position{line: 54, col: 12, offset: 1128},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 54, col: 12, offset: 1128},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 54, col: 18, offset: 1134},
								name: "AddExpr",
							},
						},
						&labeledExpr{
							pos:   position{line: 54, col: 26, offset: 1142},
							label: "rest",
							expr: &zeroOrOneExpr{
								pos: position{line: 54, col: 31, offset: 1147},
								expr: &seqExpr{
									pos: position{line: 54, col: 32, offset: 1148},
									exprs: []interface{}{
										&oneOrMoreExpr{
											pos: position{line: 54, col: 32, offset: 1148},
											expr: &ruleRefExpr{
												pos:  position{line: 54, col: 32, offset: 1148},
												name: "_",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 54, col: 35, offset: 1151},
											name: "CmpOp",
										},
										&oneOrMoreExpr{
											pos: position{line: 54, col: 41, offset: 1157},
											expr: &ruleRefExpr{
												pos:  position{line: 54, col: 41, offset: 1157},
												name: "_",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 54, col: 44, offset: 1160},
											name: "AddExpr",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "AddOp",
			pos:  position{line: 58, col: 1, offset: 1245},
			expr: &actionExpr{
				pos: position{line: 58, col: 10, offset: 1256},
				run: (*parser).callonAddOp1,
				expr: &choiceExpr{
					pos: position{line: 58, col: 11, offset: 1257},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 58, col: 11, offset: 1257},
							val:        "+",
							ignoreCase: false,
							want:       "\"+\"",
						},
						&litMatcher{
							pos:        position{line: 58, col: 17, offset: 1263},
							val:        "-",
							ignoreCase: false,
							want:       "\"-\"",
						},
					},
				},
			},
		},
		{
			name: "AddExpr",
			pos:  position{line: 61, col: 1, offset: 1291},
			expr: &actionExpr{
				pos: position{line: 61, col: 12, offset: 1304},
				run: (*parser).callonAddExpr1,
				expr: &seqExpr{
					pos: position{line: 61, col: 12, offset: 1304},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 61, col: 12, offset: 1304},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 61, col: 18, offset: 1310},
								name: "MulExpr",
							},
						},
						&labeledExpr{
							pos:   position{line: 61, col: 26, offset: 1318},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 61, col: 31, offset: 1323},
								expr: &seqExpr{
									pos: position{line: 61, col: 32, offset: 1324},
									exprs: []interface{}{
										&oneOrMoreExpr{
											pos: position{line: 61, col: 32, offset: 1324},
											expr: &ruleRefExpr{
												pos:  position{line: 61, col: 32, offset: 1324},
												name: "_",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 61, col: 35, offset: 1327},
											name: "AddOp",
										},
										&oneOrMoreExpr{
											pos: position{line: 61, col: 41, offset: 1333},
											expr: &ruleRefExpr{
												pos:  position{line: 61, col: 41, offset: 1333},
												name: "_",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 61, col: 44, offset: 1336},
											name: "MulExpr",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "MulOp",
			pos:  position{line: 65, col: 1, offset: 1409},
			expr: &actionExpr{
				pos: position{line: 65, col: 10, offset: 1420},
				run: (*parser).callonMulOp1,
				expr: &choiceExpr{
					pos: position{line: 65, col: 11, offset: 1421},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 65, col: 11, offset: 1421},
							val:        "*",
							ignoreCase: false,
							want:       "\"*\"",
						},
						&litMatcher{
							pos:        position{line: 65, col: 17, offset: 1427},
							val:        "/",
							ignoreCase: false,
							want:       "\"/\"",
						},
					},
				},
			},
		},
		{
			name: "MulExpr",
			pos:  position{line: 68, col: 1, offset: 1455},
			expr: &actionExpr{
				pos: position{line: 68, col: 12, offset: 1468},
				run: (*parser).callonMulExpr1,
				expr: &seqExpr{
					pos: position{line: 68, col: 12, offset: 1468},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 68, col: 12, offset: 1468},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 68, col: 18, offset: 1474},
								name: "UnExpr",
							},
						},
						&labeledExpr{
							pos:   position{line: 68, col: 25, offset: 1481},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 68, col: 30, offset: 1486},
								expr: &seqExpr{
									pos: position{line: 68, col: 31, offset: 1487},
									exprs: []interface{}{
										&oneOrMoreExpr{
											pos: position{line: 68, col: 31, offset: 1487},
											expr: &ruleRefExpr{
												pos:  position{line: 68, col: 31, offset: 1487},
												name: "_",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 68, col: 34, offset: 1490},
											name: "MulOp",
										},
										&oneOrMoreExpr{
											pos: position{line: 68, col: 40, offset: 1496},
											expr: &ruleRefExpr{
												pos:  position{line: 68, col: 40, offset: 1496},
												name: "_",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 68, col: 43, offset: 1499},
											name: "UnExpr",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "UnOp",
			pos:  position{line: 72, col: 1, offset: 1559},
			expr: &actionExpr{
				pos: position{line: 72, col: 9, offset: 1569},
				run: (*parser).callonUnOp1,
				expr: &litMatcher{
					pos:        position{line: 72, col: 9, offset: 1569},
					val:        "!",
					ignoreCase: false,
					want:       "\"!\"",
				},
			},
		},
		{
			name: "UnExpr",
			pos:  position{line: 75, col: 1, offset: 1596},
			expr: &actionExpr{
				pos: position{line: 75, col: 11, offset: 1608},
				run: (*parser).callonUnExpr1,
				expr: &seqExpr{
					pos: position{line: 75, col: 11, offset: 1608},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 75, col: 11, offset: 1608},
							label: "op",
							expr: &zeroOrOneExpr{
								pos: position{line: 75, col: 14, offset: 1611},
								expr: &ruleRefExpr{
									pos:  position{line: 75, col: 14, offset: 1611},
									name: "UnOp",
								},
							},
						},
						&zeroOrMoreExpr{
							pos: position{line: 75, col: 20, offset: 1617},
							expr: &ruleRefExpr{
								pos:  position{line: 75, col: 20, offset: 1617},
								name: "_",
							},
						},
						&labeledExpr{
							pos:   position{line: 75, col: 23, offset: 1620},
							label: "any",
							expr: &zeroOrOneExpr{
								pos: position{line: 75, col: 27, offset: 1624},
								expr: &ruleRefExpr{
									pos:  position{line: 75, col: 27, offset: 1624},
									name: "Any",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Array",
			pos:  position{line: 89, col: 1, offset: 1888},
			expr: &choiceExpr{
				pos: position{line: 89, col: 10, offset: 1899},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 89, col: 10, offset: 1899},
						run: (*parser).callonArray2,
						expr: &seqExpr{
							pos: position{line: 89, col: 10, offset: 1899},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 89, col: 10, offset: 1899},
									val:        "[",
									ignoreCase: false,
									want:       "\"[\"",
								},
								&labeledExpr{
									pos:   position{line: 89, col: 14, offset: 1903},
									label: "seq",
									expr: &ruleRefExpr{
										pos:  position{line: 89, col: 18, offset: 1907},
										name: "Seq",
									},
								},
								&litMatcher{
									pos:        position{line: 89, col: 22, offset: 1911},
									val:        "]",
									ignoreCase: false,
									want:       "\"]\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 91, col: 5, offset: 1962},
						run: (*parser).callonArray8,
						expr: &seqExpr{
							pos: position{line: 91, col: 5, offset: 1962},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 91, col: 5, offset: 1962},
									val:        "[",
									ignoreCase: false,
									want:       "\"[\"",
								},
								&ruleRefExpr{
									pos:  position{line: 91, col: 9, offset: 1966},
									name: "Seq",
								},
								&notExpr{
									pos: position{line: 91, col: 13, offset: 1970},
									expr: &litMatcher{
										pos:        position{line: 91, col: 14, offset: 1971},
										val:        "]",
										ignoreCase: false,
										want:       "\"]\"",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Map",
			pos:  position{line: 96, col: 1, offset: 2037},
			expr: &choiceExpr{
				pos: position{line: 96, col: 8, offset: 2046},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 96, col: 8, offset: 2046},
						run: (*parser).callonMap2,
						expr: &seqExpr{
							pos: position{line: 96, col: 8, offset: 2046},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 96, col: 8, offset: 2046},
									val:        "{",
									ignoreCase: false,
									want:       "\"{\"",
								},
								&zeroOrMoreExpr{
									pos: position{line: 96, col: 12, offset: 2050},
									expr: &ruleRefExpr{
										pos:  position{line: 96, col: 12, offset: 2050},
										name: "_",
									},
								},
								&labeledExpr{
									pos:   position{line: 96, col: 15, offset: 2053},
									label: "first",
									expr: &zeroOrOneExpr{
										pos: position{line: 96, col: 21, offset: 2059},
										expr: &seqExpr{
											pos: position{line: 96, col: 22, offset: 2060},
											exprs: []interface{}{
												&ruleRefExpr{
													pos:  position{line: 96, col: 22, offset: 2060},
													name: "String",
												},
												&zeroOrMoreExpr{
													pos: position{line: 96, col: 29, offset: 2067},
													expr: &ruleRefExpr{
														pos:  position{line: 96, col: 29, offset: 2067},
														name: "_",
													},
												},
												&litMatcher{
													pos:        position{line: 96, col: 32, offset: 2070},
													val:        ":",
													ignoreCase: false,
													want:       "\":\"",
												},
												&zeroOrMoreExpr{
													pos: position{line: 96, col: 36, offset: 2074},
													expr: &ruleRefExpr{
														pos:  position{line: 96, col: 36, offset: 2074},
														name: "_",
													},
												},
												&ruleRefExpr{
													pos:  position{line: 96, col: 39, offset: 2077},
													name: "Any",
												},
											},
										},
									},
								},
								&labeledExpr{
									pos:   position{line: 96, col: 45, offset: 2083},
									label: "rest",
									expr: &zeroOrMoreExpr{
										pos: position{line: 96, col: 50, offset: 2088},
										expr: &seqExpr{
											pos: position{line: 96, col: 51, offset: 2089},
											exprs: []interface{}{
												&oneOrMoreExpr{
													pos: position{line: 96, col: 51, offset: 2089},
													expr: &ruleRefExpr{
														pos:  position{line: 96, col: 51, offset: 2089},
														name: "_",
													},
												},
												&ruleRefExpr{
													pos:  position{line: 96, col: 54, offset: 2092},
													name: "String",
												},
												&zeroOrMoreExpr{
													pos: position{line: 96, col: 61, offset: 2099},
													expr: &ruleRefExpr{
														pos:  position{line: 96, col: 61, offset: 2099},
														name: "_",
													},
												},
												&litMatcher{
													pos:        position{line: 96, col: 64, offset: 2102},
													val:        ":",
													ignoreCase: false,
													want:       "\":\"",
												},
												&zeroOrMoreExpr{
													pos: position{line: 96, col: 68, offset: 2106},
													expr: &ruleRefExpr{
														pos:  position{line: 96, col: 68, offset: 2106},
														name: "_",
													},
												},
												&ruleRefExpr{
													pos:  position{line: 96, col: 71, offset: 2109},
													name: "Any",
												},
											},
										},
									},
								},
								&zeroOrMoreExpr{
									pos: position{line: 96, col: 77, offset: 2115},
									expr: &ruleRefExpr{
										pos:  position{line: 96, col: 77, offset: 2115},
										name: "_",
									},
								},
								&litMatcher{
									pos:        position{line: 96, col: 80, offset: 2118},
									val:        "}",
									ignoreCase: false,
									want:       "\"}\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 98, col: 5, offset: 2176},
						run: (*parser).callonMap32,
						expr: &seqExpr{
							pos: position{line: 98, col: 5, offset: 2176},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 98, col: 5, offset: 2176},
									val:        "{",
									ignoreCase: false,
									want:       "\"{\"",
								},
								&zeroOrMoreExpr{
									pos: position{line: 98, col: 9, offset: 2180},
									expr: &ruleRefExpr{
										pos:  position{line: 98, col: 9, offset: 2180},
										name: "_",
									},
								},
								&seqExpr{
									pos: position{line: 98, col: 13, offset: 2184},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 98, col: 13, offset: 2184},
											name: "String",
										},
										&zeroOrMoreExpr{
											pos: position{line: 98, col: 20, offset: 2191},
											expr: &ruleRefExpr{
												pos:  position{line: 98, col: 20, offset: 2191},
												name: "_",
											},
										},
										&litMatcher{
											pos:        position{line: 98, col: 23, offset: 2194},
											val:        ":",
											ignoreCase: false,
											want:       "\":\"",
										},
										&zeroOrMoreExpr{
											pos: position{line: 98, col: 27, offset: 2198},
											expr: &ruleRefExpr{
												pos:  position{line: 98, col: 27, offset: 2198},
												name: "_",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 98, col: 30, offset: 2201},
											name: "Any",
										},
									},
								},
								&zeroOrMoreExpr{
									pos: position{line: 98, col: 35, offset: 2206},
									expr: &seqExpr{
										pos: position{line: 98, col: 36, offset: 2207},
										exprs: []interface{}{
											&oneOrMoreExpr{
												pos: position{line: 98, col: 36, offset: 2207},
												expr: &ruleRefExpr{
													pos:  position{line: 98, col: 36, offset: 2207},
													name: "_",
												},
											},
											&ruleRefExpr{
												pos:  position{line: 98, col: 39, offset: 2210},
												name: "String",
											},
											&zeroOrMoreExpr{
												pos: position{line: 98, col: 46, offset: 2217},
												expr: &ruleRefExpr{
													pos:  position{line: 98, col: 46, offset: 2217},
													name: "_",
												},
											},
											&litMatcher{
												pos:        position{line: 98, col: 49, offset: 2220},
												val:        ":",
												ignoreCase: false,
												want:       "\":\"",
											},
											&zeroOrMoreExpr{
												pos: position{line: 98, col: 53, offset: 2224},
												expr: &ruleRefExpr{
													pos:  position{line: 98, col: 53, offset: 2224},
													name: "_",
												},
											},
											&ruleRefExpr{
												pos:  position{line: 98, col: 56, offset: 2227},
												name: "Any",
											},
										},
									},
								},
								&zeroOrMoreExpr{
									pos: position{line: 98, col: 62, offset: 2233},
									expr: &ruleRefExpr{
										pos:  position{line: 98, col: 62, offset: 2233},
										name: "_",
									},
								},
								&notExpr{
									pos: position{line: 98, col: 65, offset: 2236},
									expr: &litMatcher{
										pos:        position{line: 98, col: 66, offset: 2237},
										val:        "}",
										ignoreCase: false,
										want:       "\"}\"",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Null",
			pos:  position{line: 103, col: 1, offset: 2304},
			expr: &actionExpr{
				pos: position{line: 103, col: 9, offset: 2314},
				run: (*parser).callonNull1,
				expr: &litMatcher{
					pos:        position{line: 103, col: 9, offset: 2314},
					val:        "null",
					ignoreCase: false,
					want:       "\"null\"",
				},
			},
		},
		{
			name: "Boolean",
			pos:  position{line: 108, col: 1, offset: 2362},
			expr: &choiceExpr{
				pos: position{line: 108, col: 12, offset: 2375},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 108, col: 12, offset: 2375},
						run: (*parser).callonBoolean2,
						expr: &litMatcher{
							pos:        position{line: 108, col: 12, offset: 2375},
							val:        "true",
							ignoreCase: false,
							want:       "\"true\"",
						},
					},
					&actionExpr{
						pos: position{line: 110, col: 5, offset: 2420},
						run: (*parser).callonBoolean4,
						expr: &litMatcher{
							pos:        position{line: 110, col: 5, offset: 2420},
							val:        "false",
							ignoreCase: false,
							want:       "\"false\"",
						},
					},
				},
			},
		},
		{
			name: "Number",
			pos:  position{line: 115, col: 1, offset: 2499},
			expr: &actionExpr{
				pos: position{line: 115, col: 11, offset: 2511},
				run: (*parser).callonNumber1,
				expr: &seqExpr{
					pos: position{line: 115, col: 11, offset: 2511},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 115, col: 11, offset: 2511},
							expr: &litMatcher{
								pos:        position{line: 115, col: 11, offset: 2511},
								val:        "-",
								ignoreCase: false,
								want:       "\"-\"",
							},
						},
						&oneOrMoreExpr{
							pos: position{line: 115, col: 16, offset: 2516},
							expr: &ruleRefExpr{
								pos:  position{line: 115, col: 16, offset: 2516},
								name: "digit",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 115, col: 23, offset: 2523},
							expr: &seqExpr{
								pos: position{line: 115, col: 24, offset: 2524},
								exprs: []interface{}{
									&litMatcher{
										pos:        position{line: 115, col: 24, offset: 2524},
										val:        ".",
										ignoreCase: false,
										want:       "\".\"",
									},
									&oneOrMoreExpr{
										pos: position{line: 115, col: 28, offset: 2528},
										expr: &ruleRefExpr{
											pos:  position{line: 115, col: 28, offset: 2528},
											name: "digit",
										},
									},
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 115, col: 37, offset: 2537},
							expr: &seqExpr{
								pos: position{line: 115, col: 38, offset: 2538},
								exprs: []interface{}{
									&litMatcher{
										pos:        position{line: 115, col: 38, offset: 2538},
										val:        "e",
										ignoreCase: true,
										want:       "\"e\"i",
									},
									&zeroOrOneExpr{
										pos: position{line: 115, col: 43, offset: 2543},
										expr: &choiceExpr{
											pos: position{line: 115, col: 44, offset: 2544},
											alternatives: []interface{}{
												&litMatcher{
													pos:        position{line: 115, col: 44, offset: 2544},
													val:        "+",
													ignoreCase: false,
													want:       "\"+\"",
												},
												&litMatcher{
													pos:        position{line: 115, col: 50, offset: 2550},
													val:        "-",
													ignoreCase: false,
													want:       "\"-\"",
												},
											},
										},
									},
									&oneOrMoreExpr{
										pos: position{line: 115, col: 56, offset: 2556},
										expr: &ruleRefExpr{
											pos:  position{line: 115, col: 56, offset: 2556},
											name: "digit",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "String",
			pos:  position{line: 120, col: 1, offset: 2635},
			expr: &choiceExpr{
				pos: position{line: 120, col: 11, offset: 2647},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 120, col: 11, offset: 2647},
						run: (*parser).callonString2,
						expr: &seqExpr{
							pos: position{line: 120, col: 11, offset: 2647},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 120, col: 11, offset: 2647},
									val:        "\"",
									ignoreCase: false,
									want:       "\"\\\"\"",
								},
								&zeroOrMoreExpr{
									pos: position{line: 120, col: 15, offset: 2651},
									expr: &ruleRefExpr{
										pos:  position{line: 120, col: 15, offset: 2651},
										name: "runeChr",
									},
								},
								&litMatcher{
									pos:        position{line: 120, col: 24, offset: 2660},
									val:        "\"",
									ignoreCase: false,
									want:       "\"\\\"\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 122, col: 5, offset: 2719},
						run: (*parser).callonString8,
						expr: &seqExpr{
							pos: position{line: 122, col: 5, offset: 2719},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 122, col: 5, offset: 2719},
									val:        "\"",
									ignoreCase: false,
									want:       "\"\\\"\"",
								},
								&zeroOrMoreExpr{
									pos: position{line: 122, col: 9, offset: 2723},
									expr: &ruleRefExpr{
										pos:  position{line: 122, col: 9, offset: 2723},
										name: "runeChr",
									},
								},
								&notExpr{
									pos: position{line: 122, col: 18, offset: 2732},
									expr: &litMatcher{
										pos:        position{line: 122, col: 19, offset: 2733},
										val:        "\"",
										ignoreCase: false,
										want:       "\"\\\"\"",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "runeChr",
			pos:  position{line: 126, col: 1, offset: 2882},
			expr: &choiceExpr{
				pos: position{line: 126, col: 12, offset: 2895},
				alternatives: []interface{}{
					&charClassMatcher{
						pos:        position{line: 126, col: 12, offset: 2895},
						val:        "[^\"\\\\]",
						chars:      []rune{'"', '\\'},
						ignoreCase: false,
						inverted:   true,
					},
					&ruleRefExpr{
						pos:  position{line: 126, col: 21, offset: 2904},
						name: "runeEsc",
					},
				},
			},
		},
		{
			name: "runeEsc",
			pos:  position{line: 127, col: 1, offset: 2912},
			expr: &seqExpr{
				pos: position{line: 127, col: 12, offset: 2925},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 127, col: 12, offset: 2925},
						val:        "\\",
						ignoreCase: false,
						want:       "\"\\\\\"",
					},
					&choiceExpr{
						pos: position{line: 127, col: 17, offset: 2930},
						alternatives: []interface{}{
							&charClassMatcher{
								pos:        position{line: 127, col: 17, offset: 2930},
								val:        "[\"\\\\/abfnrtv]",
								chars:      []rune{'"', '\\', '/', 'a', 'b', 'f', 'n', 'r', 't', 'v'},
								ignoreCase: false,
								inverted:   false,
							},
							&seqExpr{
								pos: position{line: 128, col: 13, offset: 2958},
								exprs: []interface{}{
									&litMatcher{
										pos:        position{line: 128, col: 13, offset: 2958},
										val:        "x",
										ignoreCase: false,
										want:       "\"x\"",
									},
									&ruleRefExpr{
										pos:  position{line: 128, col: 17, offset: 2962},
										name: "hexDigit",
									},
									&ruleRefExpr{
										pos:  position{line: 128, col: 26, offset: 2971},
										name: "hexDigit",
									},
								},
							},
							&seqExpr{
								pos: position{line: 129, col: 13, offset: 2995},
								exprs: []interface{}{
									&litMatcher{
										pos:        position{line: 129, col: 13, offset: 2995},
										val:        "u",
										ignoreCase: false,
										want:       "\"u\"",
									},
									&ruleRefExpr{
										pos:  position{line: 129, col: 17, offset: 2999},
										name: "hexDigit",
									},
									&ruleRefExpr{
										pos:  position{line: 129, col: 26, offset: 3008},
										name: "hexDigit",
									},
									&ruleRefExpr{
										pos:  position{line: 129, col: 35, offset: 3017},
										name: "hexDigit",
									},
									&ruleRefExpr{
										pos:  position{line: 129, col: 44, offset: 3026},
										name: "hexDigit",
									},
								},
							},
							&seqExpr{
								pos: position{line: 130, col: 13, offset: 3050},
								exprs: []interface{}{
									&litMatcher{
										pos:        position{line: 130, col: 13, offset: 3050},
										val:        "U",
										ignoreCase: false,
										want:       "\"U\"",
									},
									&ruleRefExpr{
										pos:  position{line: 130, col: 17, offset: 3054},
										name: "hexDigit",
									},
									&ruleRefExpr{
										pos:  position{line: 130, col: 26, offset: 3063},
										name: "hexDigit",
									},
									&ruleRefExpr{
										pos:  position{line: 130, col: 35, offset: 3072},
										name: "hexDigit",
									},
									&ruleRefExpr{
										pos:  position{line: 130, col: 44, offset: 3081},
										name: "hexDigit",
									},
									&ruleRefExpr{
										pos:  position{line: 130, col: 53, offset: 3090},
										name: "hexDigit",
									},
									&ruleRefExpr{
										pos:  position{line: 130, col: 62, offset: 3099},
										name: "hexDigit",
									},
									&ruleRefExpr{
										pos:  position{line: 130, col: 71, offset: 3108},
										name: "hexDigit",
									},
									&ruleRefExpr{
										pos:  position{line: 130, col: 80, offset: 3117},
										name: "hexDigit",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "hexDigit",
			pos:  position{line: 131, col: 1, offset: 3128},
			expr: &charClassMatcher{
				pos:        position{line: 131, col: 12, offset: 3141},
				val:        "[0-9a-f]i",
				ranges:     []rune{'0', '9', 'a', 'f'},
				ignoreCase: true,
				inverted:   false,
			},
		},
		{
			name: "Symbol",
			pos:  position{line: 134, col: 1, offset: 3162},
			expr: &actionExpr{
				pos: position{line: 134, col: 11, offset: 3174},
				run: (*parser).callonSymbol1,
				expr: &seqExpr{
					pos: position{line: 134, col: 11, offset: 3174},
					exprs: []interface{}{
						&notExpr{
							pos: position{line: 134, col: 11, offset: 3174},
							expr: &choiceExpr{
								pos: position{line: 134, col: 13, offset: 3176},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 134, col: 13, offset: 3176},
										name: "Null",
									},
									&ruleRefExpr{
										pos:  position{line: 134, col: 20, offset: 3183},
										name: "Boolean",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 134, col: 29, offset: 3192},
							name: "word",
						},
						&zeroOrOneExpr{
							pos: position{line: 134, col: 34, offset: 3197},
							expr: &choiceExpr{
								pos: position{line: 134, col: 35, offset: 3198},
								alternatives: []interface{}{
									&litMatcher{
										pos:        position{line: 134, col: 35, offset: 3198},
										val:        "!",
										ignoreCase: false,
										want:       "\"!\"",
									},
									&litMatcher{
										pos:        position{line: 134, col: 41, offset: 3204},
										val:        "*",
										ignoreCase: false,
										want:       "\"*\"",
									},
									&litMatcher{
										pos:        position{line: 134, col: 47, offset: 3210},
										val:        "?",
										ignoreCase: false,
										want:       "\"?\"",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "word",
			pos:  position{line: 139, col: 1, offset: 3260},
			expr: &seqExpr{
				pos: position{line: 139, col: 9, offset: 3270},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 139, col: 9, offset: 3270},
						name: "letter",
					},
					&zeroOrMoreExpr{
						pos: position{line: 139, col: 16, offset: 3277},
						expr: &choiceExpr{
							pos: position{line: 139, col: 17, offset: 3278},
							alternatives: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 139, col: 17, offset: 3278},
									name: "letter",
								},
								&ruleRefExpr{
									pos:  position{line: 139, col: 26, offset: 3287},
									name: "digit",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "letter",
			pos:  position{line: 141, col: 1, offset: 3328},
			expr: &choiceExpr{
				pos: position{line: 141, col: 11, offset: 3340},
				alternatives: []interface{}{
					&charClassMatcher{
						pos:        position{line: 141, col: 11, offset: 3340},
						val:        "[\\p{L}]",
						classes:    []*unicode.RangeTable{rangeTable("L")},
						ignoreCase: false,
						inverted:   false,
					},
					&litMatcher{
						pos:        position{line: 141, col: 21, offset: 3350},
						val:        "_",
						ignoreCase: false,
						want:       "\"_\"",
					},
				},
			},
		},
		{
			name: "digit",
			pos:  position{line: 143, col: 1, offset: 3366},
			expr: &charClassMatcher{
				pos:        position{line: 143, col: 10, offset: 3377},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 146, col: 1, offset: 3436},
			expr: &choiceExpr{
				pos: position{line: 146, col: 19, offset: 3456},
				alternatives: []interface{}{
					&charClassMatcher{
						pos:        position{line: 146, col: 19, offset: 3456},
						val:        "[\\p{Z}]",
						classes:    []*unicode.RangeTable{rangeTable("Z")},
						ignoreCase: false,
						inverted:   false,
					},
					&charClassMatcher{
						pos:        position{line: 146, col: 29, offset: 3466},
						val:        "[\\p{C}]",
						classes:    []*unicode.RangeTable{rangeTable("C")},
						ignoreCase: false,
						inverted:   false,
					},
					&litMatcher{
						pos:        position{line: 146, col: 39, offset: 3476},
						val:        ",",
						ignoreCase: false,
						want:       "\",\"",
					},
					&ruleRefExpr{
						pos:  position{line: 146, col: 45, offset: 3482},
						name: "Comment",
					},
				},
			},
		},
		{
			name: "Comment",
			pos:  position{line: 148, col: 1, offset: 3502},
			expr: &choiceExpr{
				pos: position{line: 148, col: 12, offset: 3515},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 148, col: 12, offset: 3515},
						name: "SingleLineComment",
					},
					&ruleRefExpr{
						pos:  position{line: 148, col: 32, offset: 3535},
						name: "MultiLineComment",
					},
				},
			},
		},
		{
			name: "SingleLineComment",
			pos:  position{line: 149, col: 1, offset: 3552},
			expr: &seqExpr{
				pos: position{line: 149, col: 21, offset: 3574},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 149, col: 21, offset: 3574},
						val:        "//",
						ignoreCase: false,
						want:       "\"//\"",
					},
					&zeroOrMoreExpr{
						pos: position{line: 149, col: 26, offset: 3579},
						expr: &seqExpr{
							pos: position{line: 149, col: 27, offset: 3580},
							exprs: []interface{}{
								&notExpr{
									pos: position{line: 149, col: 27, offset: 3580},
									expr: &ruleRefExpr{
										pos:  position{line: 149, col: 28, offset: 3581},
										name: "EOL",
									},
								},
								&anyMatcher{
									line: 149, col: 32, offset: 3585,
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 149, col: 36, offset: 3589},
						name: "EOL",
					},
				},
			},
		},
		{
			name: "MultiLineComment",
			pos:  position{line: 150, col: 1, offset: 3593},
			expr: &seqExpr{
				pos: position{line: 150, col: 21, offset: 3615},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 150, col: 21, offset: 3615},
						val:        "/*",
						ignoreCase: false,
						want:       "\"/*\"",
					},
					&zeroOrMoreExpr{
						pos: position{line: 150, col: 26, offset: 3620},
						expr: &seqExpr{
							pos: position{line: 150, col: 27, offset: 3621},
							exprs: []interface{}{
								&notExpr{
									pos: position{line: 150, col: 27, offset: 3621},
									expr: &litMatcher{
										pos:        position{line: 150, col: 28, offset: 3622},
										val:        "*/",
										ignoreCase: false,
										want:       "\"*/\"",
									},
								},
								&anyMatcher{
									line: 150, col: 33, offset: 3627,
								},
							},
						},
					},
					&litMatcher{
						pos:        position{line: 150, col: 37, offset: 3631},
						val:        "*/",
						ignoreCase: false,
						want:       "\"*/\"",
					},
				},
			},
		},
		{
			name: "EOL",
			pos:  position{line: 153, col: 1, offset: 3652},
			expr: &choiceExpr{
				pos: position{line: 153, col: 8, offset: 3661},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 153, col: 8, offset: 3661},
						val:        "\n",
						ignoreCase: false,
						want:       "\"\\n\"",
					},
					&ruleRefExpr{
						pos:  position{line: 153, col: 15, offset: 3668},
						name: "EOF",
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 155, col: 1, offset: 3687},
			expr: &notExpr{
				pos: position{line: 155, col: 8, offset: 3696},
				expr: &anyMatcher{
					line: 155, col: 9, offset: 3697,
				},
			},
		},
	},
}

func (c *current) onAST1(seq interface{}) (interface{}, error) {
	return ast.Expr(seq.([]ast.Any)), nil
}

func (p *parser) callonAST1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAST1(stack["seq"])
}

func (c *current) onSeq2(first, rest interface{}) (interface{}, error) {
	return join(first, rest, 1), nil
}

func (p *parser) callonSeq2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSeq2(stack["first"], stack["rest"])
}

func (c *current) onSeq16(infix interface{}) (interface{}, error) {
	return infix, nil
}

func (p *parser) callonSeq16() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSeq16(stack["infix"])
}

func (c *current) onExpr2(seq interface{}) (interface{}, error) {
	return ast.Expr(seq.([]ast.Any)), nil
}

func (p *parser) callonExpr2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpr2(stack["seq"])
}

func (c *current) onExpr8() (interface{}, error) {
	return ast.Null{}, errors.New("not terminated")
}

func (p *parser) callonExpr8() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpr8()
}

func (c *current) onOrOp1() (interface{}, error) {
	return symbol(c)
}

func (p *parser) callonOrOp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrOp1()
}

func (c *current) onOrExpr1(first, rest interface{}) (interface{}, error) {
	return swap(first, rest, 1, 3), nil
}

func (p *parser) callonOrExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrExpr1(stack["first"], stack["rest"])
}

func (c *current) onAndOp1() (interface{}, error) {
	return symbol(c)
}

func (p *parser) callonAndOp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAndOp1()
}

func (c *current) onAndExpr1(first, rest interface{}) (interface{}, error) {
	return swap(first, rest, 1, 3), nil
}

func (p *parser) callonAndExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAndExpr1(stack["first"], stack["rest"])
}

func (c *current) onEqlOp1() (interface{}, error) {
	return symbol(c)
}

func (p *parser) callonEqlOp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEqlOp1()
}

func (c *current) onEqlExpr1(first, rest interface{}) (interface{}, error) {
	return swap(first, []interface{}{rest}, 1, 3), nil
}

func (p *parser) callonEqlExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEqlExpr1(stack["first"], stack["rest"])
}

func (c *current) onCmpOp1() (interface{}, error) {
	return symbol(c)
}

func (p *parser) callonCmpOp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCmpOp1()
}

func (c *current) onCmpExpr1(first, rest interface{}) (interface{}, error) {
	return swap(first, []interface{}{rest}, 1, 3), nil
}

func (p *parser) callonCmpExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCmpExpr1(stack["first"], stack["rest"])
}

func (c *current) onAddOp1() (interface{}, error) {
	return symbol(c)
}

func (p *parser) callonAddOp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAddOp1()
}

func (c *current) onAddExpr1(first, rest interface{}) (interface{}, error) {
	return swap(first, rest, 1, 3), nil
}

func (p *parser) callonAddExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAddExpr1(stack["first"], stack["rest"])
}

func (c *current) onMulOp1() (interface{}, error) {
	return symbol(c)
}

func (p *parser) callonMulOp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMulOp1()
}

func (c *current) onMulExpr1(first, rest interface{}) (interface{}, error) {
	return swap(first, rest, 1, 3), nil
}

func (p *parser) callonMulExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMulExpr1(stack["first"], stack["rest"])
}

func (c *current) onUnOp1() (interface{}, error) {
	return symbol(c)
}

func (p *parser) callonUnOp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnOp1()
}

func (c *current) onUnExpr1(op, any interface{}) (interface{}, error) {
	if op == nil && any == nil {
		return []ast.Any{}, nil
	}
	if op == nil {
		return []ast.Any{any.(ast.Any)}, nil
	}
	if any == nil {
		return []ast.Any{op.(ast.Symbol)}, nil
	}
	return []ast.Any{op.(ast.Symbol), any.(ast.Any)}, nil
}

func (p *parser) callonUnExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnExpr1(stack["op"], stack["any"])
}

func (c *current) onArray2(seq interface{}) (interface{}, error) {
	return ast.Array(seq.([]ast.Any)), nil
}

func (p *parser) callonArray2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArray2(stack["seq"])
}

func (c *current) onArray8() (interface{}, error) {
	return ast.Null{}, errors.New("not terminated")
}

func (p *parser) callonArray8() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArray8()
}

func (c *current) onMap2(first, rest interface{}) (interface{}, error) {
	return ast.Map(merge(first, rest, 0, 4)), nil
}

func (p *parser) callonMap2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMap2(stack["first"], stack["rest"])
}

func (c *current) onMap32() (interface{}, error) {
	return ast.Null{}, errors.New("not terminated")
}

func (p *parser) callonMap32() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMap32()
}

func (c *current) onNull1() (interface{}, error) {
	return ast.Null{}, nil
}

func (p *parser) callonNull1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNull1()
}

func (c *current) onBoolean2() (interface{}, error) {
	return ast.Boolean(true), nil
}

func (p *parser) callonBoolean2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBoolean2()
}

func (c *current) onBoolean4() (interface{}, error) {
	return ast.Boolean(false), nil
}

func (p *parser) callonBoolean4() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBoolean4()
}

func (c *current) onNumber1() (interface{}, error) {
	return ast.NewNumberFromString(string(c.text))
}

func (p *parser) callonNumber1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumber1()
}

func (c *current) onString2() (interface{}, error) {
	return ast.NewStringFromString(string(c.text))
}

func (p *parser) callonString2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onString2()
}

func (c *current) onString8() (interface{}, error) {
	return ast.Null{}, errors.New("not terminated")
}

func (p *parser) callonString8() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onString8()
}

func (c *current) onSymbol1() (interface{}, error) {
	return symbol(c)
}

func (p *parser) callonSymbol1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSymbol1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//     input := "input"
//     stats := Stats{}
//     _, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//     if err != nil {
//         log.Panicln(err)
//     }
//     b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//     if err != nil {
//         log.Panicln(err)
//     }
//     fmt.Println(string(b))
//
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

var statePool = &sync.Pool{
	New: func() interface{} { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}

func rangeTable(class string) *unicode.RangeTable {
	if rt, ok := unicode.Categories[class]; ok {
		return rt
	}
	if rt, ok := unicode.Properties[class]; ok {
		return rt
	}
	if rt, ok := unicode.Scripts[class]; ok {
		return rt
	}

	// cannot happen
	panic(fmt.Sprintf("invalid Unicode class: %s", class))
}
