// Code generated by pigeon; DO NOT EDIT.

package parser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"

	"github.com/arizonahanson/oryx/pkg/ast"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "AST",
			pos:  position{line: 8, col: 1, offset: 76},
			expr: &actionExpr{
				pos: position{line: 8, col: 8, offset: 85},
				run: (*parser).callonAST1,
				expr: &seqExpr{
					pos: position{line: 8, col: 8, offset: 85},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 8, col: 8, offset: 85},
							label: "expr",
							expr: &zeroOrOneExpr{
								pos: position{line: 8, col: 13, offset: 90},
								expr: &ruleRefExpr{
									pos:  position{line: 8, col: 13, offset: 90},
									name: "Expr",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 8, col: 19, offset: 96},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Any",
			pos:  position{line: 13, col: 1, offset: 137},
			expr: &choiceExpr{
				pos: position{line: 13, col: 8, offset: 146},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 13, col: 8, offset: 146},
						name: "Null",
					},
					&ruleRefExpr{
						pos:  position{line: 13, col: 15, offset: 153},
						name: "Boolean",
					},
					&ruleRefExpr{
						pos:  position{line: 13, col: 25, offset: 163},
						name: "Number",
					},
					&ruleRefExpr{
						pos:  position{line: 13, col: 34, offset: 172},
						name: "String",
					},
					&ruleRefExpr{
						pos:  position{line: 13, col: 43, offset: 181},
						name: "Array",
					},
					&ruleRefExpr{
						pos:  position{line: 13, col: 51, offset: 189},
						name: "Map",
					},
					&ruleRefExpr{
						pos:  position{line: 13, col: 57, offset: 195},
						name: "Symbol",
					},
					&ruleRefExpr{
						pos:  position{line: 13, col: 66, offset: 204},
						name: "SExpr",
					},
				},
			},
		},
		{
			name: "Null",
			pos:  position{line: 16, col: 1, offset: 219},
			expr: &actionExpr{
				pos: position{line: 16, col: 9, offset: 229},
				run: (*parser).callonNull1,
				expr: &litMatcher{
					pos:        position{line: 16, col: 9, offset: 229},
					val:        "null",
					ignoreCase: false,
					want:       "\"null\"",
				},
			},
		},
		{
			name: "Boolean",
			pos:  position{line: 21, col: 1, offset: 277},
			expr: &choiceExpr{
				pos: position{line: 21, col: 12, offset: 290},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 21, col: 12, offset: 290},
						run: (*parser).callonBoolean2,
						expr: &litMatcher{
							pos:        position{line: 21, col: 12, offset: 290},
							val:        "true",
							ignoreCase: false,
							want:       "\"true\"",
						},
					},
					&actionExpr{
						pos: position{line: 23, col: 5, offset: 335},
						run: (*parser).callonBoolean4,
						expr: &litMatcher{
							pos:        position{line: 23, col: 5, offset: 335},
							val:        "false",
							ignoreCase: false,
							want:       "\"false\"",
						},
					},
				},
			},
		},
		{
			name: "Number",
			pos:  position{line: 28, col: 1, offset: 414},
			expr: &actionExpr{
				pos: position{line: 28, col: 11, offset: 426},
				run: (*parser).callonNumber1,
				expr: &seqExpr{
					pos: position{line: 28, col: 11, offset: 426},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 28, col: 11, offset: 426},
							expr: &litMatcher{
								pos:        position{line: 28, col: 11, offset: 426},
								val:        "-",
								ignoreCase: false,
								want:       "\"-\"",
							},
						},
						&oneOrMoreExpr{
							pos: position{line: 28, col: 16, offset: 431},
							expr: &ruleRefExpr{
								pos:  position{line: 28, col: 16, offset: 431},
								name: "digit",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 28, col: 23, offset: 438},
							expr: &seqExpr{
								pos: position{line: 28, col: 24, offset: 439},
								exprs: []interface{}{
									&litMatcher{
										pos:        position{line: 28, col: 24, offset: 439},
										val:        ".",
										ignoreCase: false,
										want:       "\".\"",
									},
									&oneOrMoreExpr{
										pos: position{line: 28, col: 28, offset: 443},
										expr: &ruleRefExpr{
											pos:  position{line: 28, col: 28, offset: 443},
											name: "digit",
										},
									},
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 28, col: 37, offset: 452},
							expr: &seqExpr{
								pos: position{line: 28, col: 38, offset: 453},
								exprs: []interface{}{
									&litMatcher{
										pos:        position{line: 28, col: 38, offset: 453},
										val:        "e",
										ignoreCase: true,
										want:       "\"e\"i",
									},
									&zeroOrOneExpr{
										pos: position{line: 28, col: 43, offset: 458},
										expr: &choiceExpr{
											pos: position{line: 28, col: 44, offset: 459},
											alternatives: []interface{}{
												&litMatcher{
													pos:        position{line: 28, col: 44, offset: 459},
													val:        "+",
													ignoreCase: false,
													want:       "\"+\"",
												},
												&litMatcher{
													pos:        position{line: 28, col: 50, offset: 465},
													val:        "-",
													ignoreCase: false,
													want:       "\"-\"",
												},
											},
										},
									},
									&oneOrMoreExpr{
										pos: position{line: 28, col: 56, offset: 471},
										expr: &ruleRefExpr{
											pos:  position{line: 28, col: 56, offset: 471},
											name: "digit",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "String",
			pos:  position{line: 33, col: 1, offset: 550},
			expr: &choiceExpr{
				pos: position{line: 33, col: 11, offset: 562},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 33, col: 11, offset: 562},
						run: (*parser).callonString2,
						expr: &seqExpr{
							pos: position{line: 33, col: 11, offset: 562},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 33, col: 11, offset: 562},
									val:        "\"",
									ignoreCase: false,
									want:       "\"\\\"\"",
								},
								&zeroOrMoreExpr{
									pos: position{line: 33, col: 15, offset: 566},
									expr: &ruleRefExpr{
										pos:  position{line: 33, col: 15, offset: 566},
										name: "runeChr",
									},
								},
								&litMatcher{
									pos:        position{line: 33, col: 24, offset: 575},
									val:        "\"",
									ignoreCase: false,
									want:       "\"\\\"\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 35, col: 5, offset: 634},
						run: (*parser).callonString8,
						expr: &seqExpr{
							pos: position{line: 35, col: 5, offset: 634},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 35, col: 5, offset: 634},
									val:        "\"",
									ignoreCase: false,
									want:       "\"\\\"\"",
								},
								&zeroOrMoreExpr{
									pos: position{line: 35, col: 9, offset: 638},
									expr: &ruleRefExpr{
										pos:  position{line: 35, col: 9, offset: 638},
										name: "runeChr",
									},
								},
								&notExpr{
									pos: position{line: 35, col: 18, offset: 647},
									expr: &litMatcher{
										pos:        position{line: 35, col: 19, offset: 648},
										val:        "\"",
										ignoreCase: false,
										want:       "\"\\\"\"",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "runeChr",
			pos:  position{line: 39, col: 1, offset: 797},
			expr: &choiceExpr{
				pos: position{line: 39, col: 12, offset: 810},
				alternatives: []interface{}{
					&charClassMatcher{
						pos:        position{line: 39, col: 12, offset: 810},
						val:        "[^\"\\\\]",
						chars:      []rune{'"', '\\'},
						ignoreCase: false,
						inverted:   true,
					},
					&ruleRefExpr{
						pos:  position{line: 39, col: 21, offset: 819},
						name: "runeEsc",
					},
				},
			},
		},
		{
			name: "runeEsc",
			pos:  position{line: 40, col: 1, offset: 827},
			expr: &seqExpr{
				pos: position{line: 40, col: 12, offset: 840},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 40, col: 12, offset: 840},
						val:        "\\",
						ignoreCase: false,
						want:       "\"\\\\\"",
					},
					&choiceExpr{
						pos: position{line: 40, col: 17, offset: 845},
						alternatives: []interface{}{
							&charClassMatcher{
								pos:        position{line: 40, col: 17, offset: 845},
								val:        "[\"\\\\/abfnrtv]",
								chars:      []rune{'"', '\\', '/', 'a', 'b', 'f', 'n', 'r', 't', 'v'},
								ignoreCase: false,
								inverted:   false,
							},
							&seqExpr{
								pos: position{line: 41, col: 13, offset: 873},
								exprs: []interface{}{
									&litMatcher{
										pos:        position{line: 41, col: 13, offset: 873},
										val:        "x",
										ignoreCase: false,
										want:       "\"x\"",
									},
									&ruleRefExpr{
										pos:  position{line: 41, col: 17, offset: 877},
										name: "hexDigit",
									},
									&ruleRefExpr{
										pos:  position{line: 41, col: 26, offset: 886},
										name: "hexDigit",
									},
								},
							},
							&seqExpr{
								pos: position{line: 42, col: 13, offset: 910},
								exprs: []interface{}{
									&litMatcher{
										pos:        position{line: 42, col: 13, offset: 910},
										val:        "u",
										ignoreCase: false,
										want:       "\"u\"",
									},
									&ruleRefExpr{
										pos:  position{line: 42, col: 17, offset: 914},
										name: "hexDigit",
									},
									&ruleRefExpr{
										pos:  position{line: 42, col: 26, offset: 923},
										name: "hexDigit",
									},
									&ruleRefExpr{
										pos:  position{line: 42, col: 35, offset: 932},
										name: "hexDigit",
									},
									&ruleRefExpr{
										pos:  position{line: 42, col: 44, offset: 941},
										name: "hexDigit",
									},
								},
							},
							&seqExpr{
								pos: position{line: 43, col: 13, offset: 965},
								exprs: []interface{}{
									&litMatcher{
										pos:        position{line: 43, col: 13, offset: 965},
										val:        "U",
										ignoreCase: false,
										want:       "\"U\"",
									},
									&ruleRefExpr{
										pos:  position{line: 43, col: 17, offset: 969},
										name: "hexDigit",
									},
									&ruleRefExpr{
										pos:  position{line: 43, col: 26, offset: 978},
										name: "hexDigit",
									},
									&ruleRefExpr{
										pos:  position{line: 43, col: 35, offset: 987},
										name: "hexDigit",
									},
									&ruleRefExpr{
										pos:  position{line: 43, col: 44, offset: 996},
										name: "hexDigit",
									},
									&ruleRefExpr{
										pos:  position{line: 43, col: 53, offset: 1005},
										name: "hexDigit",
									},
									&ruleRefExpr{
										pos:  position{line: 43, col: 62, offset: 1014},
										name: "hexDigit",
									},
									&ruleRefExpr{
										pos:  position{line: 43, col: 71, offset: 1023},
										name: "hexDigit",
									},
									&ruleRefExpr{
										pos:  position{line: 43, col: 80, offset: 1032},
										name: "hexDigit",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "hexDigit",
			pos:  position{line: 44, col: 1, offset: 1043},
			expr: &charClassMatcher{
				pos:        position{line: 44, col: 12, offset: 1056},
				val:        "[0-9a-f]i",
				ranges:     []rune{'0', '9', 'a', 'f'},
				ignoreCase: true,
				inverted:   false,
			},
		},
		{
			name: "Array",
			pos:  position{line: 47, col: 1, offset: 1076},
			expr: &choiceExpr{
				pos: position{line: 47, col: 10, offset: 1087},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 47, col: 10, offset: 1087},
						run: (*parser).callonArray2,
						expr: &seqExpr{
							pos: position{line: 47, col: 10, offset: 1087},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 47, col: 10, offset: 1087},
									val:        "[",
									ignoreCase: false,
									want:       "\"[\"",
								},
								&labeledExpr{
									pos:   position{line: 47, col: 14, offset: 1091},
									label: "list",
									expr: &zeroOrOneExpr{
										pos: position{line: 47, col: 19, offset: 1096},
										expr: &ruleRefExpr{
											pos:  position{line: 47, col: 19, offset: 1096},
											name: "Mat",
										},
									},
								},
								&litMatcher{
									pos:        position{line: 47, col: 24, offset: 1101},
									val:        "]",
									ignoreCase: false,
									want:       "\"]\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 52, col: 5, offset: 1181},
						run: (*parser).callonArray9,
						expr: &seqExpr{
							pos: position{line: 52, col: 5, offset: 1181},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 52, col: 5, offset: 1181},
									val:        "[",
									ignoreCase: false,
									want:       "\"[\"",
								},
								&zeroOrOneExpr{
									pos: position{line: 52, col: 9, offset: 1185},
									expr: &ruleRefExpr{
										pos:  position{line: 52, col: 9, offset: 1185},
										name: "Mat",
									},
								},
								&notExpr{
									pos: position{line: 52, col: 14, offset: 1190},
									expr: &litMatcher{
										pos:        position{line: 52, col: 15, offset: 1191},
										val:        "]",
										ignoreCase: false,
										want:       "\"]\"",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Mat",
			pos:  position{line: 55, col: 1, offset: 1249},
			expr: &actionExpr{
				pos: position{line: 55, col: 8, offset: 1258},
				run: (*parser).callonMat1,
				expr: &seqExpr{
					pos: position{line: 55, col: 8, offset: 1258},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 55, col: 8, offset: 1258},
							label: "first",
							expr: &zeroOrOneExpr{
								pos: position{line: 55, col: 14, offset: 1264},
								expr: &ruleRefExpr{
									pos:  position{line: 55, col: 14, offset: 1264},
									name: "List",
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 55, col: 20, offset: 1270},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 55, col: 25, offset: 1275},
								expr: &seqExpr{
									pos: position{line: 55, col: 26, offset: 1276},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 55, col: 26, offset: 1276},
											val:        ";",
											ignoreCase: false,
											want:       "\";\"",
										},
										&zeroOrOneExpr{
											pos: position{line: 55, col: 30, offset: 1280},
											expr: &ruleRefExpr{
												pos:  position{line: 55, col: 30, offset: 1280},
												name: "List",
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "List",
			pos:  position{line: 66, col: 1, offset: 1503},
			expr: &actionExpr{
				pos: position{line: 66, col: 9, offset: 1513},
				run: (*parser).callonList1,
				expr: &labeledExpr{
					pos:   position{line: 66, col: 9, offset: 1513},
					label: "list",
					expr: &choiceExpr{
						pos: position{line: 66, col: 15, offset: 1519},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 66, col: 15, offset: 1519},
								name: "Seq",
							},
							&ruleRefExpr{
								pos:  position{line: 66, col: 21, offset: 1525},
								name: "Unary",
							},
						},
					},
				},
			},
		},
		{
			name: "Seq",
			pos:  position{line: 70, col: 1, offset: 1609},
			expr: &actionExpr{
				pos: position{line: 70, col: 8, offset: 1618},
				run: (*parser).callonSeq1,
				expr: &seqExpr{
					pos: position{line: 70, col: 8, offset: 1618},
					exprs: []interface{}{
						&zeroOrMoreExpr{
							pos: position{line: 70, col: 8, offset: 1618},
							expr: &ruleRefExpr{
								pos:  position{line: 70, col: 8, offset: 1618},
								name: "_",
							},
						},
						&labeledExpr{
							pos:   position{line: 70, col: 11, offset: 1621},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 70, col: 17, offset: 1627},
								name: "Any",
							},
						},
						&labeledExpr{
							pos:   position{line: 70, col: 21, offset: 1631},
							label: "rest",
							expr: &oneOrMoreExpr{
								pos: position{line: 70, col: 26, offset: 1636},
								expr: &seqExpr{
									pos: position{line: 70, col: 27, offset: 1637},
									exprs: []interface{}{
										&oneOrMoreExpr{
											pos: position{line: 70, col: 27, offset: 1637},
											expr: &ruleRefExpr{
												pos:  position{line: 70, col: 27, offset: 1637},
												name: "_",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 70, col: 30, offset: 1640},
											name: "Any",
										},
									},
								},
							},
						},
						&zeroOrMoreExpr{
							pos: position{line: 70, col: 36, offset: 1646},
							expr: &ruleRefExpr{
								pos:  position{line: 70, col: 36, offset: 1646},
								name: "_",
							},
						},
					},
				},
			},
		},
		{
			name: "Map",
			pos:  position{line: 75, col: 1, offset: 1696},
			expr: &choiceExpr{
				pos: position{line: 75, col: 8, offset: 1705},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 75, col: 8, offset: 1705},
						run: (*parser).callonMap2,
						expr: &seqExpr{
							pos: position{line: 75, col: 8, offset: 1705},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 75, col: 8, offset: 1705},
									val:        "{",
									ignoreCase: false,
									want:       "\"{\"",
								},
								&zeroOrMoreExpr{
									pos: position{line: 75, col: 12, offset: 1709},
									expr: &ruleRefExpr{
										pos:  position{line: 75, col: 12, offset: 1709},
										name: "_",
									},
								},
								&labeledExpr{
									pos:   position{line: 75, col: 15, offset: 1712},
									label: "first",
									expr: &zeroOrOneExpr{
										pos: position{line: 75, col: 21, offset: 1718},
										expr: &seqExpr{
											pos: position{line: 75, col: 22, offset: 1719},
											exprs: []interface{}{
												&ruleRefExpr{
													pos:  position{line: 75, col: 22, offset: 1719},
													name: "String",
												},
												&zeroOrMoreExpr{
													pos: position{line: 75, col: 29, offset: 1726},
													expr: &ruleRefExpr{
														pos:  position{line: 75, col: 29, offset: 1726},
														name: "_",
													},
												},
												&litMatcher{
													pos:        position{line: 75, col: 32, offset: 1729},
													val:        ":",
													ignoreCase: false,
													want:       "\":\"",
												},
												&zeroOrMoreExpr{
													pos: position{line: 75, col: 36, offset: 1733},
													expr: &ruleRefExpr{
														pos:  position{line: 75, col: 36, offset: 1733},
														name: "_",
													},
												},
												&ruleRefExpr{
													pos:  position{line: 75, col: 39, offset: 1736},
													name: "Any",
												},
											},
										},
									},
								},
								&labeledExpr{
									pos:   position{line: 75, col: 45, offset: 1742},
									label: "rest",
									expr: &zeroOrMoreExpr{
										pos: position{line: 75, col: 50, offset: 1747},
										expr: &seqExpr{
											pos: position{line: 75, col: 51, offset: 1748},
											exprs: []interface{}{
												&oneOrMoreExpr{
													pos: position{line: 75, col: 51, offset: 1748},
													expr: &ruleRefExpr{
														pos:  position{line: 75, col: 51, offset: 1748},
														name: "_",
													},
												},
												&ruleRefExpr{
													pos:  position{line: 75, col: 54, offset: 1751},
													name: "String",
												},
												&zeroOrMoreExpr{
													pos: position{line: 75, col: 61, offset: 1758},
													expr: &ruleRefExpr{
														pos:  position{line: 75, col: 61, offset: 1758},
														name: "_",
													},
												},
												&litMatcher{
													pos:        position{line: 75, col: 64, offset: 1761},
													val:        ":",
													ignoreCase: false,
													want:       "\":\"",
												},
												&zeroOrMoreExpr{
													pos: position{line: 75, col: 68, offset: 1765},
													expr: &ruleRefExpr{
														pos:  position{line: 75, col: 68, offset: 1765},
														name: "_",
													},
												},
												&ruleRefExpr{
													pos:  position{line: 75, col: 71, offset: 1768},
													name: "Any",
												},
											},
										},
									},
								},
								&zeroOrMoreExpr{
									pos: position{line: 75, col: 77, offset: 1774},
									expr: &ruleRefExpr{
										pos:  position{line: 75, col: 77, offset: 1774},
										name: "_",
									},
								},
								&litMatcher{
									pos:        position{line: 75, col: 80, offset: 1777},
									val:        "}",
									ignoreCase: false,
									want:       "\"}\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 77, col: 5, offset: 1835},
						run: (*parser).callonMap32,
						expr: &seqExpr{
							pos: position{line: 77, col: 5, offset: 1835},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 77, col: 5, offset: 1835},
									val:        "{",
									ignoreCase: false,
									want:       "\"{\"",
								},
								&zeroOrMoreExpr{
									pos: position{line: 77, col: 9, offset: 1839},
									expr: &ruleRefExpr{
										pos:  position{line: 77, col: 9, offset: 1839},
										name: "_",
									},
								},
								&seqExpr{
									pos: position{line: 77, col: 13, offset: 1843},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 77, col: 13, offset: 1843},
											name: "String",
										},
										&zeroOrMoreExpr{
											pos: position{line: 77, col: 20, offset: 1850},
											expr: &ruleRefExpr{
												pos:  position{line: 77, col: 20, offset: 1850},
												name: "_",
											},
										},
										&litMatcher{
											pos:        position{line: 77, col: 23, offset: 1853},
											val:        ":",
											ignoreCase: false,
											want:       "\":\"",
										},
										&zeroOrMoreExpr{
											pos: position{line: 77, col: 27, offset: 1857},
											expr: &ruleRefExpr{
												pos:  position{line: 77, col: 27, offset: 1857},
												name: "_",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 77, col: 30, offset: 1860},
											name: "Any",
										},
									},
								},
								&zeroOrMoreExpr{
									pos: position{line: 77, col: 35, offset: 1865},
									expr: &seqExpr{
										pos: position{line: 77, col: 36, offset: 1866},
										exprs: []interface{}{
											&oneOrMoreExpr{
												pos: position{line: 77, col: 36, offset: 1866},
												expr: &ruleRefExpr{
													pos:  position{line: 77, col: 36, offset: 1866},
													name: "_",
												},
											},
											&ruleRefExpr{
												pos:  position{line: 77, col: 39, offset: 1869},
												name: "String",
											},
											&zeroOrMoreExpr{
												pos: position{line: 77, col: 46, offset: 1876},
												expr: &ruleRefExpr{
													pos:  position{line: 77, col: 46, offset: 1876},
													name: "_",
												},
											},
											&litMatcher{
												pos:        position{line: 77, col: 49, offset: 1879},
												val:        ":",
												ignoreCase: false,
												want:       "\":\"",
											},
											&zeroOrMoreExpr{
												pos: position{line: 77, col: 53, offset: 1883},
												expr: &ruleRefExpr{
													pos:  position{line: 77, col: 53, offset: 1883},
													name: "_",
												},
											},
											&ruleRefExpr{
												pos:  position{line: 77, col: 56, offset: 1886},
												name: "Any",
											},
										},
									},
								},
								&zeroOrMoreExpr{
									pos: position{line: 77, col: 62, offset: 1892},
									expr: &ruleRefExpr{
										pos:  position{line: 77, col: 62, offset: 1892},
										name: "_",
									},
								},
								&notExpr{
									pos: position{line: 77, col: 65, offset: 1895},
									expr: &litMatcher{
										pos:        position{line: 77, col: 66, offset: 1896},
										val:        "}",
										ignoreCase: false,
										want:       "\"}\"",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Symbol",
			pos:  position{line: 82, col: 1, offset: 1965},
			expr: &actionExpr{
				pos: position{line: 82, col: 11, offset: 1977},
				run: (*parser).callonSymbol1,
				expr: &seqExpr{
					pos: position{line: 82, col: 11, offset: 1977},
					exprs: []interface{}{
						&notExpr{
							pos: position{line: 82, col: 11, offset: 1977},
							expr: &choiceExpr{
								pos: position{line: 82, col: 13, offset: 1979},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 82, col: 13, offset: 1979},
										name: "Null",
									},
									&ruleRefExpr{
										pos:  position{line: 82, col: 20, offset: 1986},
										name: "Boolean",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 82, col: 29, offset: 1995},
							name: "word",
						},
						&zeroOrOneExpr{
							pos: position{line: 82, col: 34, offset: 2000},
							expr: &choiceExpr{
								pos: position{line: 82, col: 35, offset: 2001},
								alternatives: []interface{}{
									&litMatcher{
										pos:        position{line: 82, col: 35, offset: 2001},
										val:        "!",
										ignoreCase: false,
										want:       "\"!\"",
									},
									&litMatcher{
										pos:        position{line: 82, col: 41, offset: 2007},
										val:        "?",
										ignoreCase: false,
										want:       "\"?\"",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "SExpr",
			pos:  position{line: 87, col: 1, offset: 2053},
			expr: &choiceExpr{
				pos: position{line: 87, col: 10, offset: 2064},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 87, col: 10, offset: 2064},
						run: (*parser).callonSExpr2,
						expr: &seqExpr{
							pos: position{line: 87, col: 10, offset: 2064},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 87, col: 10, offset: 2064},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&labeledExpr{
									pos:   position{line: 87, col: 14, offset: 2068},
									label: "expr",
									expr: &zeroOrOneExpr{
										pos: position{line: 87, col: 19, offset: 2073},
										expr: &ruleRefExpr{
											pos:  position{line: 87, col: 19, offset: 2073},
											name: "Expr",
										},
									},
								},
								&litMatcher{
									pos:        position{line: 87, col: 25, offset: 2079},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 92, col: 5, offset: 2158},
						run: (*parser).callonSExpr9,
						expr: &seqExpr{
							pos: position{line: 92, col: 5, offset: 2158},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 92, col: 5, offset: 2158},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&zeroOrOneExpr{
									pos: position{line: 92, col: 9, offset: 2162},
									expr: &ruleRefExpr{
										pos:  position{line: 92, col: 9, offset: 2162},
										name: "Expr",
									},
								},
								&notExpr{
									pos: position{line: 92, col: 15, offset: 2168},
									expr: &litMatcher{
										pos:        position{line: 92, col: 16, offset: 2169},
										val:        ")",
										ignoreCase: false,
										want:       "\")\"",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Expr",
			pos:  position{line: 96, col: 1, offset: 2280},
			expr: &actionExpr{
				pos: position{line: 96, col: 9, offset: 2290},
				run: (*parser).callonExpr1,
				expr: &labeledExpr{
					pos:   position{line: 96, col: 9, offset: 2290},
					label: "expr",
					expr: &choiceExpr{
						pos: position{line: 96, col: 15, offset: 2296},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 96, col: 15, offset: 2296},
								name: "Seq",
							},
							&ruleRefExpr{
								pos:  position{line: 96, col: 21, offset: 2302},
								name: "FnExpr",
							},
						},
					},
				},
			},
		},
		{
			name: "FnOp",
			pos:  position{line: 100, col: 1, offset: 2361},
			expr: &actionExpr{
				pos: position{line: 100, col: 9, offset: 2371},
				run: (*parser).callonFnOp1,
				expr: &litMatcher{
					pos:        position{line: 100, col: 9, offset: 2371},
					val:        "=>",
					ignoreCase: false,
					want:       "\"=>\"",
				},
			},
		},
		{
			name: "FnExpr",
			pos:  position{line: 103, col: 1, offset: 2399},
			expr: &actionExpr{
				pos: position{line: 103, col: 11, offset: 2411},
				run: (*parser).callonFnExpr1,
				expr: &seqExpr{
					pos: position{line: 103, col: 11, offset: 2411},
					exprs: []interface{}{
						&zeroOrMoreExpr{
							pos: position{line: 103, col: 11, offset: 2411},
							expr: &ruleRefExpr{
								pos:  position{line: 103, col: 11, offset: 2411},
								name: "_",
							},
						},
						&labeledExpr{
							pos:   position{line: 103, col: 14, offset: 2414},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 103, col: 19, offset: 2419},
								name: "AsExpr",
							},
						},
						&labeledExpr{
							pos:   position{line: 103, col: 26, offset: 2426},
							label: "right",
							expr: &zeroOrOneExpr{
								pos: position{line: 103, col: 32, offset: 2432},
								expr: &seqExpr{
									pos: position{line: 103, col: 33, offset: 2433},
									exprs: []interface{}{
										&zeroOrMoreExpr{
											pos: position{line: 103, col: 33, offset: 2433},
											expr: &ruleRefExpr{
												pos:  position{line: 103, col: 33, offset: 2433},
												name: "_",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 103, col: 36, offset: 2436},
											name: "FnOp",
										},
										&zeroOrMoreExpr{
											pos: position{line: 103, col: 41, offset: 2441},
											expr: &ruleRefExpr{
												pos:  position{line: 103, col: 41, offset: 2441},
												name: "_",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 103, col: 44, offset: 2444},
											name: "AsExpr",
										},
									},
								},
							},
						},
						&zeroOrMoreExpr{
							pos: position{line: 103, col: 53, offset: 2453},
							expr: &ruleRefExpr{
								pos:  position{line: 103, col: 53, offset: 2453},
								name: "_",
							},
						},
					},
				},
			},
		},
		{
			name: "AsOp",
			pos:  position{line: 107, col: 1, offset: 2523},
			expr: &actionExpr{
				pos: position{line: 107, col: 9, offset: 2533},
				run: (*parser).callonAsOp1,
				expr: &litMatcher{
					pos:        position{line: 107, col: 9, offset: 2533},
					val:        ":=",
					ignoreCase: false,
					want:       "\":=\"",
				},
			},
		},
		{
			name: "AsExpr",
			pos:  position{line: 110, col: 1, offset: 2561},
			expr: &actionExpr{
				pos: position{line: 110, col: 11, offset: 2573},
				run: (*parser).callonAsExpr1,
				expr: &seqExpr{
					pos: position{line: 110, col: 11, offset: 2573},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 110, col: 11, offset: 2573},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 110, col: 16, offset: 2578},
								name: "OrExpr",
							},
						},
						&labeledExpr{
							pos:   position{line: 110, col: 23, offset: 2585},
							label: "right",
							expr: &zeroOrOneExpr{
								pos: position{line: 110, col: 29, offset: 2591},
								expr: &seqExpr{
									pos: position{line: 110, col: 30, offset: 2592},
									exprs: []interface{}{
										&zeroOrMoreExpr{
											pos: position{line: 110, col: 30, offset: 2592},
											expr: &ruleRefExpr{
												pos:  position{line: 110, col: 30, offset: 2592},
												name: "_",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 110, col: 33, offset: 2595},
											name: "AsOp",
										},
										&zeroOrMoreExpr{
											pos: position{line: 110, col: 38, offset: 2600},
											expr: &ruleRefExpr{
												pos:  position{line: 110, col: 38, offset: 2600},
												name: "_",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 110, col: 41, offset: 2603},
											name: "OrExpr",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "OrOp",
			pos:  position{line: 114, col: 1, offset: 2675},
			expr: &actionExpr{
				pos: position{line: 114, col: 9, offset: 2685},
				run: (*parser).callonOrOp1,
				expr: &litMatcher{
					pos:        position{line: 114, col: 9, offset: 2685},
					val:        "||",
					ignoreCase: false,
					want:       "\"||\"",
				},
			},
		},
		{
			name: "OrExpr",
			pos:  position{line: 117, col: 1, offset: 2713},
			expr: &actionExpr{
				pos: position{line: 117, col: 11, offset: 2725},
				run: (*parser).callonOrExpr1,
				expr: &seqExpr{
					pos: position{line: 117, col: 11, offset: 2725},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 117, col: 11, offset: 2725},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 117, col: 16, offset: 2730},
								name: "AndExpr",
							},
						},
						&labeledExpr{
							pos:   position{line: 117, col: 24, offset: 2738},
							label: "right",
							expr: &zeroOrMoreExpr{
								pos: position{line: 117, col: 30, offset: 2744},
								expr: &seqExpr{
									pos: position{line: 117, col: 31, offset: 2745},
									exprs: []interface{}{
										&zeroOrMoreExpr{
											pos: position{line: 117, col: 31, offset: 2745},
											expr: &ruleRefExpr{
												pos:  position{line: 117, col: 31, offset: 2745},
												name: "_",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 117, col: 34, offset: 2748},
											name: "OrOp",
										},
										&zeroOrMoreExpr{
											pos: position{line: 117, col: 39, offset: 2753},
											expr: &ruleRefExpr{
												pos:  position{line: 117, col: 39, offset: 2753},
												name: "_",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 117, col: 42, offset: 2756},
											name: "AndExpr",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "AndOp",
			pos:  position{line: 121, col: 1, offset: 2815},
			expr: &actionExpr{
				pos: position{line: 121, col: 10, offset: 2826},
				run: (*parser).callonAndOp1,
				expr: &litMatcher{
					pos:        position{line: 121, col: 10, offset: 2826},
					val:        "&&",
					ignoreCase: false,
					want:       "\"&&\"",
				},
			},
		},
		{
			name: "AndExpr",
			pos:  position{line: 124, col: 1, offset: 2854},
			expr: &actionExpr{
				pos: position{line: 124, col: 12, offset: 2867},
				run: (*parser).callonAndExpr1,
				expr: &seqExpr{
					pos: position{line: 124, col: 12, offset: 2867},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 124, col: 12, offset: 2867},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 124, col: 17, offset: 2872},
								name: "EqlExpr",
							},
						},
						&labeledExpr{
							pos:   position{line: 124, col: 25, offset: 2880},
							label: "right",
							expr: &zeroOrMoreExpr{
								pos: position{line: 124, col: 31, offset: 2886},
								expr: &seqExpr{
									pos: position{line: 124, col: 32, offset: 2887},
									exprs: []interface{}{
										&zeroOrMoreExpr{
											pos: position{line: 124, col: 32, offset: 2887},
											expr: &ruleRefExpr{
												pos:  position{line: 124, col: 32, offset: 2887},
												name: "_",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 124, col: 35, offset: 2890},
											name: "AndOp",
										},
										&zeroOrMoreExpr{
											pos: position{line: 124, col: 41, offset: 2896},
											expr: &ruleRefExpr{
												pos:  position{line: 124, col: 41, offset: 2896},
												name: "_",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 124, col: 44, offset: 2899},
											name: "EqlExpr",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "EqlOp",
			pos:  position{line: 128, col: 1, offset: 2963},
			expr: &actionExpr{
				pos: position{line: 128, col: 10, offset: 2974},
				run: (*parser).callonEqlOp1,
				expr: &choiceExpr{
					pos: position{line: 128, col: 11, offset: 2975},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 128, col: 11, offset: 2975},
							val:        "==",
							ignoreCase: false,
							want:       "\"==\"",
						},
						&litMatcher{
							pos:        position{line: 128, col: 18, offset: 2982},
							val:        "!=",
							ignoreCase: false,
							want:       "\"!=\"",
						},
					},
				},
			},
		},
		{
			name: "EqlExpr",
			pos:  position{line: 131, col: 1, offset: 3011},
			expr: &actionExpr{
				pos: position{line: 131, col: 12, offset: 3024},
				run: (*parser).callonEqlExpr1,
				expr: &seqExpr{
					pos: position{line: 131, col: 12, offset: 3024},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 131, col: 12, offset: 3024},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 131, col: 17, offset: 3029},
								name: "CmpExpr",
							},
						},
						&labeledExpr{
							pos:   position{line: 131, col: 25, offset: 3037},
							label: "right",
							expr: &zeroOrOneExpr{
								pos: position{line: 131, col: 31, offset: 3043},
								expr: &seqExpr{
									pos: position{line: 131, col: 32, offset: 3044},
									exprs: []interface{}{
										&zeroOrMoreExpr{
											pos: position{line: 131, col: 32, offset: 3044},
											expr: &ruleRefExpr{
												pos:  position{line: 131, col: 32, offset: 3044},
												name: "_",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 131, col: 35, offset: 3047},
											name: "EqlOp",
										},
										&zeroOrMoreExpr{
											pos: position{line: 131, col: 41, offset: 3053},
											expr: &ruleRefExpr{
												pos:  position{line: 131, col: 41, offset: 3053},
												name: "_",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 131, col: 44, offset: 3056},
											name: "CmpExpr",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "CmpOp",
			pos:  position{line: 135, col: 1, offset: 3138},
			expr: &actionExpr{
				pos: position{line: 135, col: 10, offset: 3149},
				run: (*parser).callonCmpOp1,
				expr: &choiceExpr{
					pos: position{line: 135, col: 11, offset: 3150},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 135, col: 11, offset: 3150},
							val:        "<=",
							ignoreCase: false,
							want:       "\"<=\"",
						},
						&litMatcher{
							pos:        position{line: 135, col: 18, offset: 3157},
							val:        "<",
							ignoreCase: false,
							want:       "\"<\"",
						},
						&litMatcher{
							pos:        position{line: 135, col: 24, offset: 3163},
							val:        ">=",
							ignoreCase: false,
							want:       "\">=\"",
						},
						&litMatcher{
							pos:        position{line: 135, col: 31, offset: 3170},
							val:        ">",
							ignoreCase: false,
							want:       "\">\"",
						},
					},
				},
			},
		},
		{
			name: "CmpExpr",
			pos:  position{line: 138, col: 1, offset: 3198},
			expr: &actionExpr{
				pos: position{line: 138, col: 12, offset: 3211},
				run: (*parser).callonCmpExpr1,
				expr: &seqExpr{
					pos: position{line: 138, col: 12, offset: 3211},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 138, col: 12, offset: 3211},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 138, col: 17, offset: 3216},
								name: "AddExpr",
							},
						},
						&labeledExpr{
							pos:   position{line: 138, col: 25, offset: 3224},
							label: "right",
							expr: &zeroOrOneExpr{
								pos: position{line: 138, col: 31, offset: 3230},
								expr: &seqExpr{
									pos: position{line: 138, col: 32, offset: 3231},
									exprs: []interface{}{
										&zeroOrMoreExpr{
											pos: position{line: 138, col: 32, offset: 3231},
											expr: &ruleRefExpr{
												pos:  position{line: 138, col: 32, offset: 3231},
												name: "_",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 138, col: 35, offset: 3234},
											name: "CmpOp",
										},
										&zeroOrMoreExpr{
											pos: position{line: 138, col: 41, offset: 3240},
											expr: &ruleRefExpr{
												pos:  position{line: 138, col: 41, offset: 3240},
												name: "_",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 138, col: 44, offset: 3243},
											name: "AddExpr",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "AddOp",
			pos:  position{line: 142, col: 1, offset: 3328},
			expr: &actionExpr{
				pos: position{line: 142, col: 10, offset: 3339},
				run: (*parser).callonAddOp1,
				expr: &choiceExpr{
					pos: position{line: 142, col: 11, offset: 3340},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 142, col: 11, offset: 3340},
							val:        "+",
							ignoreCase: false,
							want:       "\"+\"",
						},
						&litMatcher{
							pos:        position{line: 142, col: 17, offset: 3346},
							val:        "-",
							ignoreCase: false,
							want:       "\"-\"",
						},
					},
				},
			},
		},
		{
			name: "AddExpr",
			pos:  position{line: 145, col: 1, offset: 3374},
			expr: &actionExpr{
				pos: position{line: 145, col: 12, offset: 3387},
				run: (*parser).callonAddExpr1,
				expr: &seqExpr{
					pos: position{line: 145, col: 12, offset: 3387},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 145, col: 12, offset: 3387},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 145, col: 17, offset: 3392},
								name: "MulExpr",
							},
						},
						&labeledExpr{
							pos:   position{line: 145, col: 25, offset: 3400},
							label: "right",
							expr: &zeroOrMoreExpr{
								pos: position{line: 145, col: 31, offset: 3406},
								expr: &seqExpr{
									pos: position{line: 145, col: 32, offset: 3407},
									exprs: []interface{}{
										&zeroOrMoreExpr{
											pos: position{line: 145, col: 32, offset: 3407},
											expr: &ruleRefExpr{
												pos:  position{line: 145, col: 32, offset: 3407},
												name: "_",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 145, col: 35, offset: 3410},
											name: "AddOp",
										},
										&zeroOrMoreExpr{
											pos: position{line: 145, col: 41, offset: 3416},
											expr: &ruleRefExpr{
												pos:  position{line: 145, col: 41, offset: 3416},
												name: "_",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 145, col: 44, offset: 3419},
											name: "MulExpr",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "MulOp",
			pos:  position{line: 149, col: 1, offset: 3492},
			expr: &actionExpr{
				pos: position{line: 149, col: 10, offset: 3503},
				run: (*parser).callonMulOp1,
				expr: &choiceExpr{
					pos: position{line: 149, col: 11, offset: 3504},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 149, col: 11, offset: 3504},
							val:        "*",
							ignoreCase: false,
							want:       "\"*\"",
						},
						&litMatcher{
							pos:        position{line: 149, col: 17, offset: 3510},
							val:        "/",
							ignoreCase: false,
							want:       "\"/\"",
						},
					},
				},
			},
		},
		{
			name: "MulExpr",
			pos:  position{line: 152, col: 1, offset: 3538},
			expr: &actionExpr{
				pos: position{line: 152, col: 12, offset: 3551},
				run: (*parser).callonMulExpr1,
				expr: &seqExpr{
					pos: position{line: 152, col: 12, offset: 3551},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 152, col: 12, offset: 3551},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 152, col: 17, offset: 3556},
								name: "Unary",
							},
						},
						&labeledExpr{
							pos:   position{line: 152, col: 23, offset: 3562},
							label: "right",
							expr: &zeroOrMoreExpr{
								pos: position{line: 152, col: 29, offset: 3568},
								expr: &seqExpr{
									pos: position{line: 152, col: 30, offset: 3569},
									exprs: []interface{}{
										&zeroOrMoreExpr{
											pos: position{line: 152, col: 30, offset: 3569},
											expr: &ruleRefExpr{
												pos:  position{line: 152, col: 30, offset: 3569},
												name: "_",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 152, col: 33, offset: 3572},
											name: "MulOp",
										},
										&zeroOrMoreExpr{
											pos: position{line: 152, col: 39, offset: 3578},
											expr: &ruleRefExpr{
												pos:  position{line: 152, col: 39, offset: 3578},
												name: "_",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 152, col: 42, offset: 3581},
											name: "Unary",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "UnaOp",
			pos:  position{line: 156, col: 1, offset: 3640},
			expr: &actionExpr{
				pos: position{line: 156, col: 10, offset: 3651},
				run: (*parser).callonUnaOp1,
				expr: &litMatcher{
					pos:        position{line: 156, col: 10, offset: 3651},
					val:        "!",
					ignoreCase: false,
					want:       "\"!\"",
				},
			},
		},
		{
			name: "Unary",
			pos:  position{line: 159, col: 1, offset: 3678},
			expr: &actionExpr{
				pos: position{line: 159, col: 10, offset: 3689},
				run: (*parser).callonUnary1,
				expr: &seqExpr{
					pos: position{line: 159, col: 10, offset: 3689},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 159, col: 10, offset: 3689},
							label: "uop",
							expr: &zeroOrOneExpr{
								pos: position{line: 159, col: 14, offset: 3693},
								expr: &ruleRefExpr{
									pos:  position{line: 159, col: 14, offset: 3693},
									name: "UnaOp",
								},
							},
						},
						&zeroOrMoreExpr{
							pos: position{line: 159, col: 21, offset: 3700},
							expr: &ruleRefExpr{
								pos:  position{line: 159, col: 21, offset: 3700},
								name: "_",
							},
						},
						&labeledExpr{
							pos:   position{line: 159, col: 24, offset: 3703},
							label: "any",
							expr: &ruleRefExpr{
								pos:  position{line: 159, col: 28, offset: 3707},
								name: "Any",
							},
						},
					},
				},
			},
		},
		{
			name: "word",
			pos:  position{line: 168, col: 1, offset: 3873},
			expr: &seqExpr{
				pos: position{line: 168, col: 9, offset: 3883},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 168, col: 9, offset: 3883},
						name: "letter",
					},
					&zeroOrMoreExpr{
						pos: position{line: 168, col: 16, offset: 3890},
						expr: &choiceExpr{
							pos: position{line: 168, col: 17, offset: 3891},
							alternatives: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 168, col: 17, offset: 3891},
									name: "letter",
								},
								&ruleRefExpr{
									pos:  position{line: 168, col: 26, offset: 3900},
									name: "digit",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "letter",
			pos:  position{line: 170, col: 1, offset: 3941},
			expr: &choiceExpr{
				pos: position{line: 170, col: 11, offset: 3953},
				alternatives: []interface{}{
					&charClassMatcher{
						pos:        position{line: 170, col: 11, offset: 3953},
						val:        "[\\p{L}]",
						classes:    []*unicode.RangeTable{rangeTable("L")},
						ignoreCase: false,
						inverted:   false,
					},
					&litMatcher{
						pos:        position{line: 170, col: 21, offset: 3963},
						val:        "_",
						ignoreCase: false,
						want:       "\"_\"",
					},
				},
			},
		},
		{
			name: "digit",
			pos:  position{line: 172, col: 1, offset: 3979},
			expr: &charClassMatcher{
				pos:        position{line: 172, col: 10, offset: 3990},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 175, col: 1, offset: 4049},
			expr: &choiceExpr{
				pos: position{line: 175, col: 19, offset: 4069},
				alternatives: []interface{}{
					&charClassMatcher{
						pos:        position{line: 175, col: 19, offset: 4069},
						val:        "[\\p{Z}]",
						classes:    []*unicode.RangeTable{rangeTable("Z")},
						ignoreCase: false,
						inverted:   false,
					},
					&charClassMatcher{
						pos:        position{line: 175, col: 29, offset: 4079},
						val:        "[\\p{C}]",
						classes:    []*unicode.RangeTable{rangeTable("C")},
						ignoreCase: false,
						inverted:   false,
					},
					&litMatcher{
						pos:        position{line: 175, col: 39, offset: 4089},
						val:        ",",
						ignoreCase: false,
						want:       "\",\"",
					},
					&ruleRefExpr{
						pos:  position{line: 175, col: 45, offset: 4095},
						name: "Comment",
					},
				},
			},
		},
		{
			name: "Comment",
			pos:  position{line: 177, col: 1, offset: 4115},
			expr: &choiceExpr{
				pos: position{line: 177, col: 12, offset: 4128},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 177, col: 12, offset: 4128},
						name: "SingleLineComment",
					},
					&ruleRefExpr{
						pos:  position{line: 177, col: 32, offset: 4148},
						name: "MultiLineComment",
					},
				},
			},
		},
		{
			name: "SingleLineComment",
			pos:  position{line: 178, col: 1, offset: 4165},
			expr: &seqExpr{
				pos: position{line: 178, col: 21, offset: 4187},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 178, col: 21, offset: 4187},
						val:        "//",
						ignoreCase: false,
						want:       "\"//\"",
					},
					&zeroOrMoreExpr{
						pos: position{line: 178, col: 26, offset: 4192},
						expr: &seqExpr{
							pos: position{line: 178, col: 27, offset: 4193},
							exprs: []interface{}{
								&notExpr{
									pos: position{line: 178, col: 27, offset: 4193},
									expr: &ruleRefExpr{
										pos:  position{line: 178, col: 28, offset: 4194},
										name: "EOL",
									},
								},
								&anyMatcher{
									line: 178, col: 32, offset: 4198,
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 178, col: 36, offset: 4202},
						name: "EOL",
					},
				},
			},
		},
		{
			name: "MultiLineComment",
			pos:  position{line: 179, col: 1, offset: 4206},
			expr: &seqExpr{
				pos: position{line: 179, col: 21, offset: 4228},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 179, col: 21, offset: 4228},
						val:        "/*",
						ignoreCase: false,
						want:       "\"/*\"",
					},
					&zeroOrMoreExpr{
						pos: position{line: 179, col: 26, offset: 4233},
						expr: &seqExpr{
							pos: position{line: 179, col: 27, offset: 4234},
							exprs: []interface{}{
								&notExpr{
									pos: position{line: 179, col: 27, offset: 4234},
									expr: &litMatcher{
										pos:        position{line: 179, col: 28, offset: 4235},
										val:        "*/",
										ignoreCase: false,
										want:       "\"*/\"",
									},
								},
								&anyMatcher{
									line: 179, col: 33, offset: 4240,
								},
							},
						},
					},
					&litMatcher{
						pos:        position{line: 179, col: 37, offset: 4244},
						val:        "*/",
						ignoreCase: false,
						want:       "\"*/\"",
					},
				},
			},
		},
		{
			name: "EOL",
			pos:  position{line: 182, col: 1, offset: 4265},
			expr: &choiceExpr{
				pos: position{line: 182, col: 8, offset: 4274},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 182, col: 8, offset: 4274},
						val:        "\n",
						ignoreCase: false,
						want:       "\"\\n\"",
					},
					&ruleRefExpr{
						pos:  position{line: 182, col: 15, offset: 4281},
						name: "EOF",
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 184, col: 1, offset: 4300},
			expr: &notExpr{
				pos: position{line: 184, col: 8, offset: 4309},
				expr: &anyMatcher{
					line: 184, col: 9, offset: 4310,
				},
			},
		},
	},
}

func (c *current) onAST1(expr interface{}) (interface{}, error) {
	return expr, nil
}

func (p *parser) callonAST1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAST1(stack["expr"])
}

func (c *current) onNull1() (interface{}, error) {
	return ast.Null{}, nil
}

func (p *parser) callonNull1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNull1()
}

func (c *current) onBoolean2() (interface{}, error) {
	return ast.Boolean(true), nil
}

func (p *parser) callonBoolean2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBoolean2()
}

func (c *current) onBoolean4() (interface{}, error) {
	return ast.Boolean(false), nil
}

func (p *parser) callonBoolean4() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBoolean4()
}

func (c *current) onNumber1() (interface{}, error) {
	return ast.NewNumberFromString(string(c.text))
}

func (p *parser) callonNumber1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumber1()
}

func (c *current) onString2() (interface{}, error) {
	return ast.NewStringFromString(string(c.text))
}

func (p *parser) callonString2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onString2()
}

func (c *current) onString8() (interface{}, error) {
	return ast.Null{}, errors.New("not terminated")
}

func (p *parser) callonString8() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onString8()
}

func (c *current) onArray2(list interface{}) (interface{}, error) {
	if list == nil {
		return ast.Array{}, nil
	}
	return list, nil
}

func (p *parser) callonArray2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArray2(stack["list"])
}

func (c *current) onArray9() (interface{}, error) {
	return ast.Null{}, errors.New("not terminated")
}

func (p *parser) callonArray9() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArray9()
}

func (c *current) onMat1(first, rest interface{}) (interface{}, error) {
	mat := join(first, rest, 1)
	if len(slice(rest)) == 0 {
		if first == nil {
			return ast.Array{}, nil
		}
		return first.(ast.Array), nil
	}
	return ast.Array(mat), nil
}

func (p *parser) callonMat1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMat1(stack["first"], stack["rest"])
}

func (c *current) onList1(list interface{}) (interface{}, error) {
	return ast.Array(list.([]ast.Any)), nil
}

func (p *parser) callonList1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onList1(stack["list"])
}

func (c *current) onSeq1(first, rest interface{}) (interface{}, error) {
	return join(first, rest, 1), nil
}

func (p *parser) callonSeq1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSeq1(stack["first"], stack["rest"])
}

func (c *current) onMap2(first, rest interface{}) (interface{}, error) {
	return ast.Map(merge(first, rest, 0, 4)), nil
}

func (p *parser) callonMap2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMap2(stack["first"], stack["rest"])
}

func (c *current) onMap32() (interface{}, error) {
	return ast.Null{}, errors.New("not terminated")
}

func (p *parser) callonMap32() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMap32()
}

func (c *current) onSymbol1() (interface{}, error) {
	return symbol(c)
}

func (p *parser) callonSymbol1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSymbol1()
}

func (c *current) onSExpr2(expr interface{}) (interface{}, error) {
	if expr == nil {
		return ast.Expr{}, nil
	}
	return expr, nil
}

func (p *parser) callonSExpr2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSExpr2(stack["expr"])
}

func (c *current) onSExpr9() (interface{}, error) {
	return ast.Null{}, errors.New("not terminated")
}

func (p *parser) callonSExpr9() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSExpr9()
}

func (c *current) onExpr1(expr interface{}) (interface{}, error) {
	return ast.Expr(expr.([]ast.Any)), nil
}

func (p *parser) callonExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpr1(stack["expr"])
}

func (c *current) onFnOp1() (interface{}, error) {
	return symbol(c)
}

func (p *parser) callonFnOp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFnOp1()
}

func (c *current) onFnExpr1(left, right interface{}) (interface{}, error) {
	return swap(left, []interface{}{right}, 1, 3), nil
}

func (p *parser) callonFnExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFnExpr1(stack["left"], stack["right"])
}

func (c *current) onAsOp1() (interface{}, error) {
	return symbol(c)
}

func (p *parser) callonAsOp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAsOp1()
}

func (c *current) onAsExpr1(left, right interface{}) (interface{}, error) {
	return swap(left, []interface{}{right}, 1, 3), nil
}

func (p *parser) callonAsExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAsExpr1(stack["left"], stack["right"])
}

func (c *current) onOrOp1() (interface{}, error) {
	return symbol(c)
}

func (p *parser) callonOrOp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrOp1()
}

func (c *current) onOrExpr1(left, right interface{}) (interface{}, error) {
	return swap(left, right, 1, 3), nil
}

func (p *parser) callonOrExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrExpr1(stack["left"], stack["right"])
}

func (c *current) onAndOp1() (interface{}, error) {
	return symbol(c)
}

func (p *parser) callonAndOp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAndOp1()
}

func (c *current) onAndExpr1(left, right interface{}) (interface{}, error) {
	return swap(left, right, 1, 3), nil
}

func (p *parser) callonAndExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAndExpr1(stack["left"], stack["right"])
}

func (c *current) onEqlOp1() (interface{}, error) {
	return symbol(c)
}

func (p *parser) callonEqlOp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEqlOp1()
}

func (c *current) onEqlExpr1(left, right interface{}) (interface{}, error) {
	return swap(left, []interface{}{right}, 1, 3), nil
}

func (p *parser) callonEqlExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEqlExpr1(stack["left"], stack["right"])
}

func (c *current) onCmpOp1() (interface{}, error) {
	return symbol(c)
}

func (p *parser) callonCmpOp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCmpOp1()
}

func (c *current) onCmpExpr1(left, right interface{}) (interface{}, error) {
	return swap(left, []interface{}{right}, 1, 3), nil
}

func (p *parser) callonCmpExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCmpExpr1(stack["left"], stack["right"])
}

func (c *current) onAddOp1() (interface{}, error) {
	return symbol(c)
}

func (p *parser) callonAddOp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAddOp1()
}

func (c *current) onAddExpr1(left, right interface{}) (interface{}, error) {
	return swap(left, right, 1, 3), nil
}

func (p *parser) callonAddExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAddExpr1(stack["left"], stack["right"])
}

func (c *current) onMulOp1() (interface{}, error) {
	return symbol(c)
}

func (p *parser) callonMulOp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMulOp1()
}

func (c *current) onMulExpr1(left, right interface{}) (interface{}, error) {
	return swap(left, right, 1, 3), nil
}

func (p *parser) callonMulExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMulExpr1(stack["left"], stack["right"])
}

func (c *current) onUnaOp1() (interface{}, error) {
	return symbol(c)
}

func (p *parser) callonUnaOp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnaOp1()
}

func (c *current) onUnary1(uop, any interface{}) (interface{}, error) {
	if uop != nil {
		return []ast.Any{uop.(ast.Symbol), any.(ast.Any)}, nil
	}
	// no-operator
	return []ast.Any{any.(ast.Any)}, nil
}

func (p *parser) callonUnary1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnary1(stack["uop"], stack["any"])
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//     input := "input"
//     stats := Stats{}
//     _, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//     if err != nil {
//         log.Panicln(err)
//     }
//     b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//     if err != nil {
//         log.Panicln(err)
//     }
//     fmt.Println(string(b))
//
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

var statePool = &sync.Pool{
	New: func() interface{} { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}

func rangeTable(class string) *unicode.RangeTable {
	if rt, ok := unicode.Categories[class]; ok {
		return rt
	}
	if rt, ok := unicode.Properties[class]; ok {
		return rt
	}
	if rt, ok := unicode.Scripts[class]; ok {
		return rt
	}

	// cannot happen
	panic(fmt.Sprintf("invalid Unicode class: %s", class))
}
